<?php

	require_once( LANG_UI_PATH . 'activate.php' );

	if ($this->playerStatus == 0 - 1) {
		echo '<h6>';
		echo LANGUI_ACTIVATE_T1;
		echo '</h6>
<p><b>';
		echo LANGUI_ACTIVATE_T2;
		echo '</b></p>
<p class="f10 e b">';
		echo LANGUI_ACTIVATE_T3;
		echo ':</p>
<div class="f10">
	<li><p>';
		echo LANGUI_ACTIVATE_T4;
		echo '</p></li>
	<li><p>';
		echo LANGUI_ACTIVATE_T5;
		echo '</p></li>
	<li><p>';
		echo LANGUI_ACTIVATE_T6;
		echo '</p></li>
	<li><p>';
		echo LANGUI_ACTIVATE_T7;
		echo '</p></li>
</div>
';

		if (0 < $this->uid) {
			echo '<p><b><br><br>';
			echo LANGUI_ACTIVATE_T8;
			echo '.</b></p>
<form action="activate.php?uid=';
			echo $this->uid;
			echo '" method="post">
<table cellpadding="1" cellspacing="1">
	<tbody>
		<tr class="top">
			<th>';
			echo LANGUI_ACTIVATE_T9;
			echo ':</th>
			<td class="name">';
			echo $this->uname;
			echo '</td>
		</tr>
		<tr class="btm">
			<th>';
			echo LANGUI_ACTIVATE_T10;
			echo '</th>
			<td><input class="text" type="password" name="pw" maxlength="20"></td>
		</tr>
	</tbody>
</table>
<p class="btn"><input type="image" src="assets/x.gif" class="dynamic_img " id="btn_delete" alt="';
			echo LANGUI_ACTIVATE_T11;
			echo '" value="';
			echo LANGUI_ACTIVATE_T11;
			echo '" name="delreports"></p>
</form>
';
			return 1;
		}
	} 
else {
		if ($this->playerStatus == 3) {
			echo '<p class="info2">';
			echo LANGUI_ACTIVATE_T12;
			echo '</p>
<p><a href="register.php">';
			echo LANGUI_ACTIVATE_T13;
			echo '</a></p>
';
			return 1;
		}


		if ($this->playerStatus == 1) {
			echo '<p class="f9">';
			echo LANGUI_ACTIVATE_T14;
			echo '.</p>
<p class="f9">';
			echo LANGUI_ACTIVATE_T15;
			echo ' <a href="index.php">';
			echo LANGUI_ACTIVATE_T16;
			echo '</a></p>
';
			return 1;
		}


		if ($this->playerStatus == 2) {
			echo '<p class="f9">';
			echo LANGUI_ACTIVATE_T17;
			echo '.</p>
';
		}
	}

?>


