<?php

	require_once( LANG_UI_PATH . 'badwords.php' );
	echo '<h1>';
	echo LANGUI_BADWORDS_T1;
	echo '</h1>
<form action="badwords.php" method="POST">
<table cellpadding="1" cellspacing="1" id="links">
	<thead>
		<tr>
			<th colspan="2">';
	echo LANGUI_BADWORDS_T2;
	echo '</th>
		</tr>
		<tr>
			<td>';
	echo LANGUI_BADWORDS_T3;
	echo '</td>
            <td>';
	echo LANGUI_BADWORDS_T4;
	echo '</td>
		</tr>
	</thead>
	<tbody>
   ';
	$i = 1;

	while ($i <= 10) {
		echo '		<tr>
			<td class="nr">';
		echo $i;
		echo '</td>
			<td class="nam"><input class="text" type="text" name="words[]" value="" maxlength="150"></td>
		</tr>
        ';
		++$i;
	}

	echo '        <tr>
        	<td colspan="2"><div class="btn"><input type="image" value="" name="s1" id="btn_ok" class="dynamic_img" src="assets/x.gif" title="';
	echo LANGUI_BADWORDS_T8;
	echo '" alt="';
	echo LANGUI_BADWORDS_T8;
	echo '"></div></td>
        </tr>
    </tbody>
</table><br />
<table cellpadding="1" cellspacing="1" id="links">
	<thead>
		<tr>
			<th colspan="3">';
	echo LANGUI_BADWORDS_T5;
	echo '</th>
		</tr>
		<tr>
			<td>';
	echo LANGUI_BADWORDS_T3;
	echo '</td>
            <td>';
	echo LANGUI_BADWORDS_T4;
	echo '</td>
            <td>';
	echo LANGUI_BADWORDS_T6;
	echo '</td>
		</tr>
	</thead>
	<tbody>
		';
	$_c = 0;

	while ($this->BadWords->next()) {
		++$_c;
		$c = $_c + $this->pageIndex * $this->pageSize;
		echo '		<tr>
			<td class="nr">';
		echo $c++;
		echo '</td>
			<td class="nam">';
		echo htmlspecialchars( $this->BadWords->row['word'] );
		echo '</td>
			<td class="link"><a href="badwords.php?Dword=';
		echo htmlspecialchars( $this->BadWords->row['ID'] );
		echo '"><img alt="';
		echo LANGUI_BADWORDS_T7;
		echo '" title="';
		echo LANGUI_BADWORDS_T7;
		echo '" border="0" src="assets/default/img/a/del.gif" /></a></td>
		</tr>
		';
	}

	echo '        <tr>
            <td colspan="2" class="table_body"><div align="center">';
	echo $this->getPreviousLink();
	echo ' &nbsp; | &nbsp; ';
	echo $this->getNextLink();
	echo '</div></td>
            <td class="table_body"><div align="center">
			';
	echo '<s';
	echo 'elect name="p" onchange="window.location.href=(\'badwords.php?p=\'+this.value)">
            ';
	$i = 1;
	$c = 0;

	while ($i <= $this->pageCount) {
		echo '            	<option value="';
		echo $c;
		echo '"';

		if (( isset( $_GET['p'] ) && $_GET['p'] == $c )) {
			echo ' selected="selected"';
		}

		echo '>';
		echo $i;
		echo '</option>
            ';
		++$i;
		++$c;
	}

	echo '            </select>
            </div></td>
        </tr>
	</tbody>
</table>
</form>';
?>


