<?php

	echo '﻿';
	require_once( LANG_UI_PATH . 'index.php' );
	echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3c.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="eg" lang="eg">
	<head>
		<title>';
	echo $this->appConfig['page'][$this->appConfig['system']['lang'] . '_title'];
	echo '</title>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta http-equiv="content-script-type" content="text/javascript" />
		<meta http-equiv="content-style-type" content="text/css" />
		<meta content="';
	echo $this->appConfig['page']['meta-tag'];
	echo '" name="description"> 
		<meta content="';
	echo $this->appConfig['page']['meta-tag'];
	echo '" name="keywords">
        <link rel="stylesheet" type="text/css" href="assets/indx/css/style_';
	echo $this->appConfig['system']['lang'];
	echo '.css';
	echo $this->getAssetVersion();
	echo '"/>
		<meta name="google-site-verification" content="vTjsRxnpRzHRJvw5E3uOiAA-jcGayHNOw_SEAD93-fc" />
		<link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
		';
	echo '<s';
	echo 'cript type="text/javascript">var d3l=';
	echo ($this->appConfig['system']['lang'] == 'ar' ? '180' : '-600');
	echo ';</script>
		';
	echo '<s';
	echo 'cript src="assets/core.js';
	echo $this->getAssetVersion();
	echo '" type="text/javascript"></script>
	</head>
<body>
<div style="position:absolute; top:5px; left:20px;">
<a href="" onclick="setLang(\'en\')"><img src="assets/indx/img/en.jpg" border="0" title="';
	echo LANGUI_INDX_T12;
	echo '" alt="';
	echo LANGUI_INDX_T12;
	echo '" /></a>
<a href="" onclick="setLang(\'ar\')"><img src="assets/indx/img/ar.jpg" border="0" title="';
	echo LANGUI_INDX_T11;
	echo '" alt="';
	echo LANGUI_INDX_T11;
	echo '"/></a>
</div>
<div id="allcontentts">
<div id="mokatel"></div>
	<div id="header">		
		<div class="logo"></div>
		<div class="formlogin">
		<form action="index.php" method="post" name="login">
		<input class="text';

	if ($this->errorState == 1) {
		echo ' iError';
	}

	echo '" name="name" type="text" title="';
	echo LANGUI_INDX_T1;
	echo '" value="';
	echo $this->name;
	echo '" />
		<input class="text';

	if ($this->errorState == 2) {
		echo ' iError';
	}

	echo '" name="password" type="password" title="';
	echo LANGUI_INDX_T2;
	echo '" value="';
	echo $this->password;
	echo '" />
		<input name="submit" type="submit" value="';
	echo LANGUI_INDX_T3;
	echo '" id="sub" />
		</form>
		';

	if ($this->error != '') {
		echo '<div style="background-color:#FF0000;color:#FFFFFF;padding:2px;width:300px;">' . $this->error . '</div>';
	}

	echo '		</div>
<!-- END [header] Class / ID -->
	</div>

	<div id="contentxx">
    	<div class="writeherethecont">
    		<div class="rightside">
    		<div class="rightstat"><table class="stats" cellpadding="2" cellspacing="2">
			<tr><td>';
	echo '<s';
	echo 'trong>';
	echo LANGUI_INDX_T4;
	echo ':</strong></td><td>';
	echo $this->data['players_count'];
	echo '</td></tr> 
			<tr><td>';
	echo '<s';
	echo 'trong>';
	echo LANGUI_INDX_T5;
	echo ':</strong></td><td>';
	echo $this->data['active_players_count'];
	echo '</td></tr> 
			<tr><td>';
	echo '<s';
	echo 'trong>';
	echo LANGUI_INDX_T6;
	echo ':</strong></td><td>';
	echo $this->data['online_players_count'];
	echo '</td></tr> 
		</table></div>
    		<div class="rightnews">
    			<div class="rightnehed"></div>
    			<h5 style="padding: 0px 10px 0px 10px">';
	echo nl2br( $this->data['news_text'] );
	echo '</h5>
    		</div>
    		</div>
    		<div class="leftside">
    			<!-- Content Site -->
<div class="intro">';
	echo LANGUI_INDX_T7;
	echo '</div>
<div class="buttonplay"><a href="manual.php">';
	echo '<s';
	echo 'pan>';
	echo LANGUI_INDX_T8;
	echo '</span></a></div>
<div class="sliddxx">
  <ul id="slideshow">';
	echo LANGUI_INDX_T10;
	echo '</ul>
  <div id="wrapper">
    <div id="fullsize">
      <div id="imgprev" class="imgnav" title="Previous Image"></div>
      <div id="imglink"></div>
      <div id="imgnext" class="imgnav" title="Next Image"></div>
      <div id="image"></div>
      <div id="information">
        <h3></h3>
        <p></p>
      </div>
    </div>
    <div id="thumbnails">
      <div id="slideleft" title="Slide Left"></div';
	echo '>
      <div id="slidearea">
        <div id="slider"></div>
      </div>
      <div id="slideright" title="Slide Right"></div>
    </div>
  </div>
  ';
	echo '<s';
	echo 'cript type="text/javascript" src="assets/indx/js/compressed.js';
	echo $this->getAssetVersion();
	echo '"></script> 
  ';
	echo '<s';
	echo 'cript type="text/javascript">
	$(\'slideshow\').style.display=\'none\';
	$(\'wrapper\').style.display=\'block\';
	var slideshow=new TINY.slideshow("slideshow");
	window.onload=function(){
		slideshow.auto=true;
		slideshow.speed=5;
		slideshow.link="linkhover";
		slideshow.info="information";
		slideshow.thumbs="slider";
		slideshow.left="slideleft";
		slideshow.right="slideright";
		slideshow';
	echo '.scrollSpeed=4;
		slideshow.spacing=5;
		slideshow.active="#fff";
		slideshow.init("slideshow","image","imgprev","imgnext","imglink");
	}
</script> 
</div>
<div class="register"><a href="register.php">';
	echo '<s';
	echo 'pan>';
	echo LANGUI_INDX_T9;
	echo '</span></a></div>
<div class="bannerads" align="center">
';

	if (0 < sizeof( $this->banner )) {
		if ($this->banner['type'] == 'image') {
			echo '<a target="_blank" href="banner.php?url=' . base64_encode( $this->banner['ID'] ) . '"> 
		<img height="60" width="550" src="' . $this->banner['image'] . '" border="0" title="' . $this->banner['name'] . '"  alt="' . $this->banner['name'] . '"></a> ';
		} 
else {
			echo '<embed height="60" width="550" onclick="window.location.href(\'banner.php?url=' . base64_encode( $this->banner['ID'] ) . '\')" title="' . $this->banner['name'] . '" src="' . $this->banner['image'] . '" />';
		}
	}

	echo '</div>
<div class="copyr">
';
	require_once( LANG_UI_PATH . 'footer.php' );
	echo '<s';
	echo 'pan><a href="manual.php">';
	echo LANGUI_FOOTER_MANUAL;
	echo '</a></span> |
';
	echo '<s';
	echo 'pan><a href="training.php">';
	echo LANGUI_FOOTER_TRAINING;
	echo '</a></span> |
';
	echo '<s';
	echo 'pan><a href="';
	echo $this->appConfig['system']['forum_url'];
	echo '" target="_blank">';
	echo LANGUI_INDX_T13;
	echo '</a></span> |
';
	echo '<s';
	echo 'pan><a href="';
	echo $this->appConfig['system']['social_url'];
	echo '" target="_blank">';
	echo LANGUI_INDX_T14;
	echo '</a></span> |
';
	echo '<s';
	echo 'pan><a href="http://www.dboor.com" target="_blank">Copyright &copy; To dboor.com</a></span>
</div>
    		</div>
<!-- END [writeherethecont] Class / ID -->
    	</div>
<!-- END [content] Class / ID -->
	</div>

	<div id="footer">
<!-- END [footer] Class / ID -->

	</div>
<!-- END [allcontentts] Class / ID -->
</div>
</body>
';
	echo '<s';
	echo 'cript type="text/javascript">init();</script>
</html>';
?>


