<?php

	require_once( LANG_UI_PATH . 'msg.php' );
	echo '<h1>';
	echo LANGUI_MSG_T1;
	echo '</h1><div id="textmenu">   <a href="msg.php"';

	if ($this->selectedTabIndex == 0) {
		echo ' class="selected"';
	}

	echo '>';
	echo LANGUI_MSG_T2;
	echo '</a> | <a href="msg.php?t=1"';

	if ($this->selectedTabIndex == 1) {
		echo ' class="selected"';
	}

	echo '>';
	echo LANGUI_MSG_T3;
	echo '</a> | <a href="msg.php?t=2"';

	if ($this->selectedTabIndex == 2) {
		echo ' class="selected"';
	}

	echo '>';
	echo LANGUI_MSG_T4;
	echo '</a></div>';

	if ($this->showList) {
		echo '<form method="post" action="msg.php?p=';
		echo $this->pageIndex;

		if ($this->selectedTabIndex == 2) {
			echo '&t=2';
		}

		echo '" name="msg"><table cellpadding="1" cellspacing="1" id="overview" class="row_table_data">	<thead>		<tr>			<th colspan="2">';
		echo LANGUI_MSG_T5;
		echo '</th>			<th>';
		echo ($this->selectedTabIndex == 2 ? LANGUI_MSG_T6 : LANGUI_MSG_T7);
		echo '</th>			<th class="sent">';
		echo LANGUI_MSG_T8;
		echo '</th>		</tr>	</thead>	<tbody>		';
		$_c = 0;

		while ($this->dataList->next()) {
			++$_c;
			echo '		<tr>			<td class="sel"><input class="check" type="checkbox" name="dm[]" value="';
			echo $this->dataList->row['id'];
			echo '"></td>			<td class="top"><a href="msg.php?id=';
			echo $this->dataList->row['id'];
			echo '">';
			echo $this->dataList->row['msg_title'];
			echo '</a>';

			if (!$this->dataList->row['is_readed']) {
				echo ($this->selectedTabIndex == 0 ? ' ' . LANGUI_MSG_T9 : ' ' . LANGUI_MSG_T10);
			}

			echo '</td>			<td class="send">';

			if (0 < $this->dataList->row['uid']) {
				echo '<a href="profile.php?uid=';
				echo $this->dataList->row['uid'];
				echo '">';
				echo $this->dataList->row['uname'];
				echo '</a>';
			} 
else {
				echo '<s';
				echo 'pan class="none">';
				echo $this->dataList->row['uname'];
				echo '</span>';
			}

			echo '</td>			<td class="dat">';
			echo $this->dataList->row['mdate'];
			echo '</td>		</tr>		';
		}


		if ($_c == 0) {
			echo '		<tr><td colspan="4">';
			echo '<s';
			echo 'pan class="none">';
			echo LANGUI_MSG_T11;
			echo '</span></td></tr>		';
		}

		echo '	</tbody>	<tfoot>		<tr>			<th>&nbsp;</th>			<th colspan="2" class="buttons">';

		if (0 < $_c) {
			echo '<input name="delmsg" value="';
			echo LANGUI_MSG_T12;
			echo '" type="image" id="btn_delete" class="dynamic_img" src="assets/x.gif" alt="';
			echo LANGUI_MSG_T12;
			echo '">';
		}

		echo '</th>			<th class="navi">';
		echo $this->getPreviousLink();
		echo ' ';
		echo $this->getNextLink();
		echo '</th>		</tr>	</tfoot></table></form>';
		return 1;
	}

	echo '<s';
	echo 'cript language="JavaScript" type="text/javascript">	function closeFriendsList() {		_(\'adressbook\').className = \'hide\';	}		function toggleFriendsList() {		var book = _(\'adressbook\');		book.className = (book.className == \'hide\') ? \'\' : \'hide\';	}	function copyElement(element) {		if (element == \'receiver\') {			_(\'copy_receiver\').value = _(\'receiver\').value;		} else if (element == \'subject\')';
	echo ' {			_(\'copy_subject\').value = _(\'subject\').value;		} else if (element == \'body\') {			_(\'copy_igm\').value = _(\'igm\').value;		}	}	function setReceiver(name) {		_(\'receiver\').value = name;		copyElement(\'receiver\');	}	function delFriend (uid) {		_("fma").value=uid;		document.abform.submit();	}</script>';
	echo '<s';
	echo 'pan class="error">';
	echo $this->errorText;
	echo '</span><div id="write_head" class="msg_head"></div><div id="write_content" class="msg_content">	<form method="post" action="msg.php" accept-charset="UTF-8" name="msg">		<input type="hidden" name="';
	echo ($this->viewOnly ? 'rm' : 'sm');
	echo '" value="">				<img src="assets/x.gif" id="label" class="';
	echo ($this->sendMail ? 'send' : 'read');
	echo '" alt="">		<div id="heading">			<input class="text" type="text"';

	if ($this->viewOnly) {
		echo ' readonly="readonly"';
	}

	echo ' name="an" id="receiver" value="';
	echo htmlspecialchars( $this->receiver );
	echo '" maxlength="20" onkeyup="copyElement(\'receiver\')" tabindex="1;"><br>			<input class="text" type="text"';

	if ($this->viewOnly) {
		echo ' readonly="readonly"';
	}

	echo ' name="be" id="subject" value="';
	echo htmlspecialchars( $this->subject );
	echo '" maxlength="35" onkeyup="copyElement(\'subject\')" tabindex="2;">		</div>		';

	if ($this->viewOnly) {
		echo '		<div id="time">			<div>';
		echo $this->messageDate;
		echo '</div>			<div>';
		echo $this->messageTime;
		echo '</div>		</div>		';
	} 
else {
		echo '		<a id="adbook" href="#" onclick="toggleFriendsList(); return false;"><img src="assets/x.gif" alt="';
		echo LANGUI_MSG_T13;
		echo '" title="';
		echo LANGUI_MSG_T13;
		echo '"></a>		';
	}

	echo '		<div class="clear"></div>		<div id="line"></div>		<textarea class="textarea write" name="message" id="igm" onkeyup="copyElement(\'body\')" tabindex="3;"';

	if ($this->viewOnly) {
		echo ' readonly="readonly"';
	}

	echo '>';
	echo htmlspecialchars( $this->body );
	echo '</textarea>		';

	if ($this->isInbox) {
		echo '		<p class="btn">			';

		if ($this->viewOnly) {
			echo '			<input type="image" value="" name="s1" id="btn_reply" class="dynamic_img" src="assets/x.gif" alt="';
			echo LANGUI_MSG_T14;
			echo '">			';
		} 
else {
			echo '			<input type="image" value="" name="s1" id="btn_send" class="dynamic_img" src="assets/x.gif" alt="';
			echo LANGUI_MSG_T15;
			echo '" tabindex="4;">						';
		}

		echo '		</p>		';
	}

	echo '	</form>';

	if (!$this->viewOnly) {
		echo '	<div id="adressbook" class="';

		if (!$this->showFriendPane) {
			echo 'hide';
		}

		echo '">	<h2>';
		echo LANGUI_MSG_T13;
		echo '</h2>	<form method="post" name="abform" action="msg.php" accept-charset="UTF-8">		<input type="hidden" id="fma" name="fm" value="">		<input type="hidden" id="copy_receiver" name="an" value="';
		echo htmlspecialchars( $this->receiver );
		echo '">		<input type="hidden" id="copy_subject" name="be" value="';
		echo htmlspecialchars( $this->subject );
		echo '">		<input type="hidden" id="copy_igm" name="message" value="';
		echo htmlspecialchars( $this->body );
		echo '">				<table cellpadding="1" cellspacing="1" id="friendlist">			<tbody>				<tr>				';
		$_c = 1;
		foreach ($this->friendList as $friendId => $friendName) {
			echo '				<td class="end"><img onclick="delFriend(';
			echo $friendId;
			echo ')" src="assets/x.gif" class="del" title="';
			echo LANGUI_MSG_T12;
			echo '" alt="';
			echo LANGUI_MSG_T12;
			echo '"></td>				<td class="pla"><a href="#" onclick="closeFriendsList(); setReceiver(\'';
			echo htmlspecialchars( $friendName );
			echo '\'); return false;">';
			echo $friendName;
			echo '</a></td>				<td class="on"></td>				';
			echo ($_c % 2 == 0 ? '</tr>' : '<td></td>');
			echo '				';
			++$_c;
		}

		echo '							';
		$i = $_c;

		while ($i <= 20) {
			echo '				<td class="end"></td>				<td class="pla"><input class="text" type="text" name="mfriends[]" value="" maxlength="15"></td>				<td class="on"></td>				';
			echo ($i % 2 == 0 ? '</tr>' : '<td></td>');
			echo '				';
			++$i;
		}

		echo '			</tbody>		</table>		<p class="btn"><input type="image" value="" name="s1" id="btn_save" class="dynamic_img" src="assets/x.gif" alt="';
		echo text_save_lang;
		echo '"></p>	</form>	<a href="#" onclick="closeFriendsList(); return false;"><img src="assets/x.gif" id="close" alt="';
		echo LANGUI_MSG_T16;
		echo '" title="';
		echo LANGUI_MSG_T16;
		echo '"></a>	</div>';
	}

	echo '</div><div id="write_foot" class="msg_foot"></div>';

	if (0 < intval( $this->data['alliance_id'] )) {
		echo '<s';
		echo 'pan class="error">';
		echo LANGUI_MSG_T17;
		echo '</span>';
	}

?>


