<?php

	if (!$this->requestPaymentProvider) {
		echo '<s';
		echo 'tyle type="text/css"> 
html, body {
    margin: 0em;
    padding: 0em;
    background-color: #e9e9e9;
    font-size: 11px;
    font-family: Verdana, Arial, Helvetica, sans-serif;
    color: #333333;
}
div.messagebox {
    position: relative;
    margin: 75px auto 75px auto;
    padding: 20px;
    width: 300px;
    background-color: #ffffff;
    border: 2px solid #d6d6d6;
    text-a';
		echo 'lign: center;
    font-size: 15px;
    font-weight: bold;
    white-space: nowrap;
}
</style>
 
<div class="messagebox"> 
<img src="assets/default/plus/tgp-bytraviangames.png" width="191" height="252" alt=""><br><br> 
<img src="assets/default/plus/loading.gif" width="48" height="48" alt="loading"><br><br> 
';
		echo $this->title;
		echo '</div> 
 
<div id="container"></div>

<noscript>Please enable JavaScript in your Browser to continue.</noscript> 
';
		echo '<s';
		echo 'cript type="text/javascript"> 
<!--
function createRequestObject() {
    var browser = navigator.appName;
    if (browser == \'Microsoft Internet Explorer\') {
        return new ActiveXObject(\'Microsoft.XMLHTTP\');
    } else {
        return new XMLHttpRequest();
    }

    return null;
}
 
function loadProviderHtml() {
    http.open(\'get\', \'payment.php?c&p=';
		echo $_GET['p'];
		echo '&pg=';
		echo $_GET['pg'];
		echo '\');
    http.onreadystatechange     = handleLoadProviderHtmlResponse;
    http.send(null);
}
 
function handleLoadProviderHtmlResponse() {
    if (http.readyState == 4) {
        if (http.status == 200) {
            var response        = http.responseText;
            var target          = document.getElementById(\'container\');
            target.innerHTML    = response;
            doc';
		echo 'ument.payment.submit();
        } else {
            var target          = document.getElementById(\'container\');
            target.innerHTML    = \'Error: unable to load payment provider. (\'+ http.statusText +\')\';
        }
    }
}

var http = createRequestObject();
loadProviderHtml();
//-->
</script>
';
		return 1;
	}


	if ($this->providerType == 'cashu') {
		$price = $this->package['cost'];
		$token = md5( sprintf( '%s:%s:%s:%s', $this->payment['merchant_id'], $price, strtolower( $this->payment['currency'] ), ($this->payment['testMode'] ? $this->payment['testKey'] : $this->payment['key']) ) );
		$dtest = sprintf( '%s ' . text_gold_lang, $this->package['gold'] );
		echo '<form action="https://www.cashu.com/cgi-bin/pcashu.cgi" method="post" name="payment">
	';

		if ($this->payment['testMode']) {
			echo '<input type="hidden" name="test_mode" value="1">';
		}

		echo '	';

		if (trim( $this->payment['serviceName'] ) != '') {
			echo '<input type="hidden" name="service_name" value="';
			echo $this->payment['serviceName'];
			echo '">';
		}

		echo '	<input type="hidden" name="merchant_id" value="';
		echo $this->payment['merchant_id'];
		echo '">
    <input type="hidden" name="currency" value="';
		echo $this->payment['currency'];
		echo '">
    <input type="hidden" name="amount" value="';
		echo $price;
		echo '">
    <input type="hidden" name="session_id" value="';
		echo $this->secureId;
		echo '">
	<input type="hidden" name="token" value="';
		echo $token;
		echo '">
    <input type="hidden" name="display_text" value="';
		echo $dtest;
		echo '">
	<input type="hidden" name="language" value="';
		echo $this->appConfig['system']['lang'];
		echo '">
    <input type="hidden" name="txt1" value="';
		echo text_gold_lang;
		echo '">
    <input type="image" src="http://www.cashu.com/images/newModel/buyIcons/icon_a3.gif" value="Pay with cashU!">
</form>
';
		return 1;
	}


	if ($this->providerType == 'onecard') {
		$dt = date( 'ymdHis' );
		$price = $this->package['cost'];
		$token = md5( sprintf( '%s:%s:%s:%s', $this->payment['merchant_id'], $price, strtolower( $this->payment['currency'] ), ($this->payment['testMode'] ? $this->payment['testKey'] : $this->payment['key']) ) );
		$dtest = sprintf( '%s ' . text_gold_lang, $this->package['gold'] );
		$TransID = base64_encode( base64_decode( $this->secureId ) . time() );
		$txt1 = base64_decode( $this->secureId ) . '-' . $this->packageIndex . '-' . $price;
		$key = $this->payment['merchant_id'] . $TransID . $price . $this->payment['currency'] . $dt . $this->payment['key'];
		$token = md5( $key );
		echo '<form name="payment" action="http://onecard.n2vsb.com/customer/integratedPayment.html" method="post">
<input type="hidden" name="OneCard_MProd" value="Tatar War">
<input type="hidden" name="OneCard_Amount" value="';
		echo $price;
		echo '">
<input type="hidden" name="OneCard_MerchID" value="';
		echo $this->payment['merchant_id'];
		echo '">
<input type="hidden" name="OneCard_HashKey" value="';
		echo $token;
		echo '">
<input type="hidden" name="OneCard_Timein" value="';
		echo $dt;
		echo '" >
<input type="hidden" name="OneCard_ReturnURL" value = "';
		echo $this->Domain . '/paymentservice.php';
		echo '">
<input type="hidden" name="OneCard_TransID" value="';
		echo $TransID;
		echo '">
<input type="hidden" name="OneCard_Currency" value="';
		echo $this->payment['currency'];
		echo '">
<input type="hidden" name="OneCard_Field1" value="';
		echo $this->secureId;
		echo '">
<input type="hidden" name="OneCard_Field2" value="';
		echo $txt1;
		echo '">
<input id="Submit1" type="submit" value="submit" />
</form>
';
		return 1;
	}


	if ($this->providerType == 'paypal') {
		require_once( LIB_PATH . 'paypal.class.php' );
		paypal_class;
		$p = new ();

		if ($this->payment['testMode']) {
			$p->paypal_url = 'https://www.sandbox.paypal.com/cgi-bin/webscr';
		} 
else {
			$p->paypal_url = 'https://www.paypal.com/cgi-bin/webscr';
		}

		$dtest = sprintf( '%s ' . text_gold_lang, $this->package['gold'] );
		$this_script = $this->Domain . 'paymentservice_paypal.php';
		$p->add_field( 'business', $this->payment['merchant_id'] );
		$p->add_field( 'return', $this_script . '?action=success' );
		$p->add_field( 'cancel_return', $this_script . '?action=cancel' );
		$p->add_field( 'notify_url', $this_script . '?action=ipn' );
		$p->add_field( 'item_name', $dtest );
		$p->add_field( 'custom', $this->secureId );
		$p->add_field( 'bn', 'btn_buynow_SM.gif' );
		$p->add_field( 'amount', $this->package['cost'] );
		$p->add_field( 'currency_code', $this->payment['currency'] );
		$p->submit_paypal_post();
	}

?>


