<?php

	require_once( LANG_UI_PATH . 'profile.php' );
	echo '<h1>';
	echo LANGUI_PROFILE_T1;
	echo '</h1>
';

	if ($this->fullView) {
		echo '<div id="textmenu">
   <a href="profile.php"';

		if ($this->selectedTabIndex == 0) {
			echo ' class="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T2;
		echo '</a>
 | <a href="profile.php?t=1"';

		if ($this->selectedTabIndex == 1) {
			echo ' class="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T3;
		echo '</a>
 | <a href="profile.php?t=2"';

		if ($this->selectedTabIndex == 2) {
			echo ' class="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T4;
		echo '</a>
 | <a href="profile.php?t=3"';

		if ($this->selectedTabIndex == 3) {
			echo ' class="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T5;
		echo '</a>
';

		if ($this->data['player_type'] != PLAYERTYPE_TATAR) {
			echo ' | <a href="profile.php?t=4"';

			if ($this->selectedTabIndex == 4) {
				echo ' class="selected"';
			}

			echo '>';
			echo LANGUI_PROFILE_T6;
			echo '</a>';
		}

		echo '</div>
';
	}

	echo '
';

	if ($this->selectedTabIndex == 0) {
		echo '<s';
		echo 'cript type="text/javascript">
function getMouseCoords(e) {
	var coords = {};
	if (!e) var e = window.event;
	if (e.pageX || e.pageY) {
		coords.x = e.pageX;
		coords.y = e.pageY;
	} else if (e.clientX || e.clientY) {
		coords.x = e.clientX + document.body.scrollLeft + document.documentElement.scrollLeft;
		coords.y = e.clientY + document.body.scrollTop + document.documentElement.scrollTop';
		echo ';
	}

	return coords;
}
function med_mouseMoveHandler(e, desc_string) {
	var coords = getMouseCoords(e);
	var layer = _("medal_mouseover");
	layer.style.top = (coords.y + 25) + "px";
	layer.style.left = (coords.x - 20) + "px";
	layer.className = "";
	layer.innerHTML  = desc_string;
}
function med_closeDescription(){
	var layer = _("medal_mouseover");
	layer.className = "hide";
}
';
		echo '
layer = document.createElement("div");
layer.id = "medal_mouseover";
layer.className = "hide";
document.body.appendChild(layer);
</script>

<table id="profile" cellpadding="1" cellspacing="1">
	<thead>
		<tr><th colspan="2">';
		echo LANGUI_PROFILE_T7;
		echo ' ';
		echo $this->profileData['name'];
		echo ' ';

		if (( isset( $this->profileData['is_blocked'] ) && $this->profileData['is_blocked'] == 1 )) {
			'<font color="#990000">' . LANGUI_PROFILE_T70 . '</font>';
		}

		echo '</th></tr>
		<tr>
			<td>';
		echo LANGUI_PROFILE_T8;
		echo ':</td>
			<td>';
		echo LANGUI_PROFILE_T9;
		echo ':</td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td class="empty"></td><td class="empty"></td>
		</tr>
		<tr>
			<td class="details">
				<table cellpadding="0" cellspacing="0">
				<tbody>
					<tr>
						<th>';
		echo LANGUI_PROFILE_T10;
		echo ':</th>
						<td>';
		echo $this->profileData['rank'];
		echo '</td>
					</tr>
					<tr>
						<th>';
		echo LANGUI_PROFILE_T11;
		echo ':</th>
						<td>';
		echo constant( 'tribe_' . $this->profileData['tribe_id'] );
		echo '</td>
					</tr>
					<tr>
						<th>';
		echo LANGUI_PROFILE_T12;
		echo ':</th>
						<td>';

		if (0 < intval( $this->profileData['alliance_id'] )) {
			echo '<a href="alliance.php?id=';
			echo $this->profileData['alliance_id'];
			echo '">';
			echo $this->profileData['alliance_name'];
			echo '</a>';
		} 
else {
			echo '-';
		}

		echo '</td>
					</tr>
					<tr>
						<th>';
		echo LANGUI_PROFILE_T13;
		echo '</th>
						<td>';
		echo $this->villagesCount;
		echo '</td>
					</tr>
					<tr>
						<th>';
		echo LANGUI_PROFILE_T14;
		echo ':</th>
						<td>';
		echo $this->profileData['total_people_count'];
		echo '</td>
					</tr>
					';

		if (0 < $this->profileData['age']) {
			echo '					<tr>
						<th>';
			echo LANGUI_PROFILE_T15;
			echo ':</th>
						<td>';
			echo $this->profileData['age'];
			echo '</td>
					</tr>
					';
		}

		echo '					';

		if (0 < $this->profileData['gender']) {
			echo '					<tr>
						<th>';
			echo LANGUI_PROFILE_T16;
			echo ':</th>
						<td>';
			echo ($this->profileData['gender'] == 1 ? LANGUI_PROFILE_T17 : LANGUI_PROFILE_T18);
			echo '</td>
					</tr>
					';
		}

		echo '					';

		if ($this->profileData['house_name'] != '') {
			echo '					<tr>
						<th>';
			echo LANGUI_PROFILE_T19;
			echo ':</th>
						<td>';
			echo $this->profileData['house_name'];
			echo '</td>
					</tr>
					';
		}

		echo '					';

		if ($this->profileData['tribe_id'] != 5) {
			echo '					<tr><td colspan="2" class="empty"></td></tr>
					<tr>
						<td colspan="2"> ';

			if (!$this->player->isAgent) {
				if ($this->fullView) {
					echo '<a href="profile.php?t=1">';
					echo LANGUI_PROFILE_T20;
					echo '</a>';
				} 
else {
					echo '<a href="msg.php?uid=';
					echo $this->profileData['id'];
					echo '">';
					echo LANGUI_PROFILE_T21;
					echo '</a>';
				}
			}

			echo '</td>
					</tr>
					';
		}

		echo '					';

		if (( $this->isAdmin && $this->player->playerId != $this->profileData['id'] )) {
			echo '					<tr>
						<td colspan="2"><a href="profile.php?spy&uid=';
			echo $this->profileData['id'];
			echo '">';
			echo LANGUI_PROFILE_T22;
			echo '</a></td>
					</tr>
					';
		}

		echo '					';

		if ($this->profileData['tribe_id'] != 5) {
			echo '                    <tr>
						<td colspan="2"><a href="snprofile.php?uid=';
			echo $this->profileData['id'];
			echo '">';
			echo LANGUI_PROFILE_T72;
			echo '</a></td>
					</tr>
					';
		}

		echo '					<tr><td colspan="2" class="empty"></td></tr>
					<tr>
						<td colspan="2" class="desc2"><div class="desc2div">';
		echo $this->getProfileDescription( $this->profileData['description2'] );
		echo '</div></td>
					</tr>
				</tbody>
				</table>
			</td>
			<td class="desc1"><div>';
		echo $this->getProfileDescription( $this->profileData['description1'] );
		echo '</div></td>
		</tr>
	</tbody>
</table>

<table cellpadding="1" cellspacing="1" id="villages">
	<thead>
	<tr><th colspan="3">';
		echo LANGUI_PROFILE_T13;
		echo '</th></tr>
	<tr>
		<td>';
		echo LANGUI_PROFILE_T23;
		echo '</td>
		<td>';
		echo LANGUI_PROFILE_T14;
		echo '</td>
		<td>';
		echo LANGUI_PROFILE_T24;
		echo '</td>
	</tr>
	</thead>
	<tbody>
		';

		while ($this->villages->next()) {
			echo '		<tr>
			<td class="nam"><a href="village3.php?id=';
			echo $this->villages->row['id'];
			echo '">';
			echo $this->villages->row['village_name'];
			echo '</a>';

			if ($this->villages->row['is_capital']) {
				echo ' ';
				echo '<s';
				echo 'pan class="none3">(';
				echo LANGUI_PROFILE_T25;
				echo ')</span>';
			}

			echo '</td>
			<td class="hab">';
			echo $this->villages->row['people_count'];
			echo '</td>
			<td class="aligned_coords"><div class="cox">(';
			echo $this->villages->row['rel_x'];
			echo '</div><div class="pi">|</div><div class="coy">';
			echo $this->villages->row['rel_y'];
			echo ')</div></td>
		</tr>
		';
		}

		echo '	</tbody>
</table>

';
		return 1;
	}


	if ($this->selectedTabIndex == 1) {
		echo '<form action="profile.php" enctype="multipart/form-data" method="POST">
	<input type="hidden" name="e" value="1" />
	<input type="hidden" name="oldavatar" value="';
		echo htmlspecialchars( $this->profileData['avatar'] );
		echo '" />
	<table cellpadding="1" cellspacing="1" id="edit" class="vip">
		<thead>
			<tr>
				<th colspan="3">';
		echo LANGUI_PROFILE_T7;
		echo ' ';
		echo $this->profileData['name'];
		echo '</th>
			</tr>
			<tr>
				<td colspan="2">';
		echo LANGUI_PROFILE_T8;
		echo ':</td>
				<td>';
		echo LANGUI_PROFILE_T9;
		echo ':</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td colspan="2" class="empty"></td><td class="empty"></td>
			</tr>
			<tr>
				<th>';
		echo LANGUI_PROFILE_T26;
		echo ':</th>
				<td class="birth">
					<input tabindex="3" type="text" name="jahr" value="';

		if (0 < $this->birthDate['year']) {
			echo $this->birthDate['year'];
		}

		echo '" maxlength="4" class="text year">
					';
		echo '<s';
		echo 'elect tabindex="2" name="monat" size="0" class="dropdown">
						<option value="0"></option>
						<option value="1"';

		if ($this->birthDate['month'] == 1) {
			echo ' selected="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T27;
		echo '</option>
						<option value="2"';

		if ($this->birthDate['month'] == 2) {
			echo ' selected="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T28;
		echo '</option>
						<option value="3"';

		if ($this->birthDate['month'] == 3) {
			echo ' selected="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T29;
		echo '</option>
						<option value="4"';

		if ($this->birthDate['month'] == 4) {
			echo ' selected="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T30;
		echo '</option>
						<option value="5"';

		if ($this->birthDate['month'] == 5) {
			echo ' selected="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T31;
		echo '</option>
						<option value="6"';

		if ($this->birthDate['month'] == 6) {
			echo ' selected="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T32;
		echo '</option>
						<option value="7"';

		if ($this->birthDate['month'] == 7) {
			echo ' selected="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T33;
		echo '</option>
						<option value="8"';

		if ($this->birthDate['month'] == 8) {
			echo ' selected="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T34;
		echo '</option>
						<option value="9"';

		if ($this->birthDate['month'] == 9) {
			echo ' selected="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T35;
		echo '</option>
						<option value="10"';

		if ($this->birthDate['month'] == 10) {
			echo ' selected="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T36;
		echo '</option>
						<option value="11"';

		if ($this->birthDate['month'] == 11) {
			echo ' selected="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T37;
		echo '</option>
						<option value="12"';

		if ($this->birthDate['month'] == 12) {
			echo ' selected="selected"';
		}

		echo '>';
		echo LANGUI_PROFILE_T38;
		echo '</option>
					</select>
					<input tabindex="1" class="text day" type="text" name="tag" value="';

		if (0 < $this->birthDate['day']) {
			echo $this->birthDate['day'];
		}

		echo '" maxlength="2">
				</td>
				<td rowspan="8" class="desc1"><textarea tabindex="7" name="be1">';
		echo $this->profileData['description1'];
		echo '</textarea></td>
			</tr>
			<tr>
				<th>';
		echo LANGUI_PROFILE_T16;
		echo ':</th>
				<td class="gend">
					<label><input class="radio" type="radio" name="mw" value="0"';

		if ($this->profileData['gender'] == 0) {
			echo '  checked="" tabindex="4"';
		}

		echo '>';
		echo LANGUI_PROFILE_T39;
		echo '</label>
					<label><input class="radio" type="radio" name="mw" value="1"';

		if ($this->profileData['gender'] == 1) {
			echo '  checked="" tabindex="4"';
		}

		echo '>';
		echo LANGUI_PROFILE_T40;
		echo '</label>
					<label><input class="radio" type="radio" name="mw" value="2"';

		if ($this->profileData['gender'] == 2) {
			echo '  checked="" tabindex="4"';
		}

		echo '>';
		echo LANGUI_PROFILE_T41;
		echo '</label>
				</td>
			</tr>
			<tr>
				<th>';
		echo LANGUI_PROFILE_T19;
		echo ':</th>
				<td><input tabindex="5" type="text" name="ort" value="';
		echo htmlspecialchars( $this->profileData['house_name'] );
		echo '" maxlength="30" class="text" /></td>
			</tr>
			<tr><td colspan="2" class="empty"></td></tr>
			<tr>
				<th>';
		echo LANGUI_PROFILE_T42;
		echo ':</th>
				<td><input tabindex="6" type="text" name="dname" value="';
		echo htmlspecialchars( $this->profileData['village_name'] );
		echo '" maxlength="20" class="text" /></td>
			</tr>
            <tr>
			  <th>';
		echo LANGUI_PROFILE_T71;
		echo ':</th>
			  <td><input tabindex="10" type="file" name="avatar" class="text" /></td>
	      </tr>
			<tr><td colspan="2" class="empty"></td></tr>
			<tr><td colspan="2" class="desc2"><textarea tabindex="8" name="be2">';
		echo $this->profileData['description2'];
		echo '</textarea></td></tr>
		</tbody>
	</table>

	<table cellpadding="1" cellspacing="1" id="medals">
		<thead>
			<tr><th colspan="4">';
		echo LANGUI_PROFILE_T43;
		echo '</th></tr>
			<tr>
				<td>';
		echo LANGUI_PROFILE_T44;
		echo '</td>
				<td>';
		echo LANGUI_PROFILE_T45;
		echo '</td>
				<td>';
		echo LANGUI_PROFILE_T46;
		echo '</td>
				<td>';
		echo LANGUI_PROFILE_T47;
		echo '</td>
			</tr>
		</thead>
		<tbody>
			';
		$medals = explode( ',', $this->profileData['medals'] );
		foreach ($medals as $medal) {
			list( $index, $rank, $week ) = explode( ':', $medal );

			if (!isset( $this->gameMetadata['medals'][$index] )) {
				continue;
			}

			$medalData = $this->gameMetadata['medals'][$index];

			if ($index == 0) {
				$rank = 1;
			}

			echo '			<tr>
			   <td class="typ">';
			echo constant( 'medal_row_' . $medalData['textIndex'] );
			echo '</td>
			   <td class="ra">';
			echo $rank;
			echo '</td>
			   <td class="we">';
			echo $week;
			echo '</td>
			   <td class="bb">[#';
			echo intval( $medalData['BBCode'] ) + intval( $week ) * 10 + ( intval( $rank ) - 1 );
			echo ']</td>
			</tr>
			';
		}

		echo '		</tbody>
	</table>
	<p class="btn"><input type="image" value="" tabindex="9" name="s1" id="btn_ok" class="dynamic_img" src="assets/x.gif" alt="';
		echo text_okdone_lang;
		echo '"></p>
</form>
';
		return 1;
	}


	if ($this->selectedTabIndex == 2) {
		echo '<form action="profile.php?t=2" method="POST">
<input type="hidden" name="e" value="2">

<table cellpadding="1" cellspacing="1" id="change_mail" class="account">
	<thead>
		<tr><th colspan="2">';
		echo LANGUI_PROFILE_T48;
		echo '</th></tr>
	</thead>
	<tbody>
		<tr><td class="note" colspan="2">';
		echo LANGUI_PROFILE_T49;
		echo '</td></tr>
		<tr>
			<th>';
		echo LANGUI_PROFILE_T50;
		echo ':</th>
			<td><input class="text" type="password" name="pw1" maxlength="20"></td>
		</tr>
		<tr>
			<th>';
		echo LANGUI_PROFILE_T51;
		echo ':</th>
			<td><input class="text" type="password" name="pw2" maxlength="20"></td>
		</tr>
		<tr>
			<th>';
		echo LANGUI_PROFILE_T51;
		echo ':</th>
			<td><input class="text" type="password" name="pw3" maxlength="20"></td>
		</tr>
	</tbody>
</table>

<table cellpadding="1" cellspacing="1" id="change_mail" class="account">
	<thead>
		<tr><th colspan="2">';
		echo LANGUI_PROFILE_T52;
		echo '</th></tr>
	</thead>
	<tbody>
		<tr><td class="note" colspan="2">';
		echo LANGUI_PROFILE_T53;
		echo '</td></tr>
		<tr>
			<th>';
		echo LANGUI_PROFILE_T54;
		echo ':</th>
			<td><input class="text" type="text" name="email_alt" maxlength="50"></td>
		</tr>
		<tr>
			<th>';
		echo LANGUI_PROFILE_T55;
		echo ':</th>
			<td><input class="text" type="text" name="email_neu" maxlength="50"></td>
		</tr>
	</tbody>
</table>
<p class="btn"><input type="image" value="" name="s1" id="btn_save" class="dynamic_img" src="assets/x.gif" alt="';
		echo text_save_lang;
		echo '"></p>
</form>
';
		return 1;
	}


	if ($this->selectedTabIndex == 3) {
		if ($this->errorText != '') {
			echo '<p class="f10 e">';
			echo $this->errorText;
			echo '</p>';
		}

		echo '<form action="profile.php?t=3" method="POST">
<input type="hidden" name="e" value="3">

<table cellpadding="1" cellspacing="1" id="sitter" class="account">
	<thead>
		<tr><th colspan="2">';
		echo LANGUI_PROFILE_T56;
		echo '</th></tr>
	</thead>
	<tbody>
		<tr><td class="note" colspan="2">';
		echo LANGUI_PROFILE_T57;
		echo '</td></tr>
		<tr>
			<th>';
		echo LANGUI_PROFILE_T58;
		echo ':</th>
			<td><input class="text" type="text" name="v1" maxlength="15"';

		if (2 <= sizeof( $this->myAgentPlayers )) {
			echo ' disabled=""';
		}

		echo '>';
		echo '<s';
		echo 'pan class="';
		echo (2 <= sizeof( $this->myAgentPlayers ) ? 'max' : 'count');
		echo '">(';
		echo sizeof( $this->myAgentPlayers );
		echo '/2)</span></td>
		</tr>
		<tr><td colspan="2" class="sitter">
		';

		if (sizeof( $this->myAgentPlayers ) == 0) {
			echo '			';
			echo '<s';
			echo 'pan class="none">';
			echo LANGUI_PROFILE_T59;
			echo '</span>
		';
		} 
else {
			foreach ($this->myAgentPlayers as $aid => $aname) {
				echo '		<div><a href="profile.php?t=3&aid=';
				echo $aid;
				echo '"><img class="del" src="assets/x.gif" title="';
				echo LANGUI_PROFILE_T60;
				echo '" alt="';
				echo LANGUI_PROFILE_T60;
				echo '"></a> <a href="profile.php?uid=';
				echo $aid;
				echo '">';
				echo $aname;
				echo '</a></div>
		';
			}
		}

		echo '		</td></tr>
		
		<tr><td class="note" colspan="2">';
		echo LANGUI_PROFILE_T61;
		echo '</td></tr>
		<tr><td colspan="2" class="sitter">
		';

		if (sizeof( $this->agentForPlayers ) == 0) {
			echo '			';
			echo '<s';
			echo 'pan class="none">';
			echo LANGUI_PROFILE_T62;
			echo '</span>
		';
		} 
else {
			foreach ($this->agentForPlayers as $aid => $aname) {
				echo '		<div><a href="profile.php?t=3&afid=';
				echo $aid;
				echo '"><img class="del" src="assets/x.gif" title="';
				echo LANGUI_PROFILE_T63;
				echo '" alt="';
				echo LANGUI_PROFILE_T63;
				echo '"></a> <a href="profile.php?uid=';
				echo $aid;
				echo '">';
				echo $aname;
				echo '</a></div>
		';
			}
		}

		echo '		</td></tr>
	</tbody>
</table>
';

		if (sizeof( $this->myAgentPlayers ) < 2) {
			echo '<p class="btn"><input type="image" value="" name="s1" id="btn_save" class="dynamic_img" src="assets/x.gif" alt="';
			echo text_save_lang;
			echo '"></p>';
		}

		echo '</form>
';
		return 1;
	}


	if ($this->selectedTabIndex == 4) {
		echo '<form action="profile.php?t=4" method="POST">
<input type="hidden" name="e" value="4">

<table cellpadding="1" cellspacing="1" id="del_acc" class="account">
	<thead>
		<tr><th colspan="2">';
		echo LANGUI_PROFILE_T6;
		echo '</th></tr>
	</thead>
	<tbody>
		<tr><td class="note" colspan="2">';
		echo LANGUI_PROFILE_T64;
		echo '</td></tr>
		';

		if ($this->isPlayerInDeletionProgress()) {
			echo '		<tr>
			<td colspan="2" class="count">
				';

			if ($this->canCancelPlayerDeletionProcess()) {
				echo '<a href="profile.php?t=4&qid=';
				echo $this->getPlayerDeletionId();
				echo '"><img class="del" src="assets/x.gif" alt="';
				echo LANGUI_PROFILE_T65;
				echo '" title="';
				echo LANGUI_PROFILE_T65;
				echo '"> ';
			}

			echo '</a>';
			echo LANGUI_PROFILE_T66;
			echo ' ';
			echo '<s';
			echo 'pan id="timer1">';
			echo $this->getPlayerDeletionTime();
			echo '</span> ';
			echo time_hour_lang;
			echo '			</td>
		</tr>
		';
		} 
else {
			echo '		<tr>
			<th>';
			echo LANGUI_PROFILE_T6;
			echo '</th>
			<td class="del_selection">
				<label><input class="radio" type="radio" name="del" value="1"> ';
			echo LANGUI_PROFILE_T67;
			echo '</label>
				<label><input class="radio" type="radio" name="del" value="0" checked=""> ';
			echo LANGUI_PROFILE_T68;
			echo '</label>
			</td>
		</tr>
		<tr>
			<th>';
			echo LANGUI_PROFILE_T69;
			echo ':</th>
			<td><input class="text" type="password" name="del_pw" maxlength="20"></td>
		</tr>
		';
		}

		echo '	</tbody>
</table>
';

		if (!$this->isPlayerInDeletionProgress()) {
			echo '<p class="btn"><input type="image" value="" name="s1" id="btn_save" class="dynamic_img" src="assets/x.gif" alt="';
			echo text_save_lang;
			echo '"></p>';
		}

		echo '</form>
';
	}

?>


