<?php

	require_once( LANG_UI_PATH . 'resources.php' );
	echo '<h1><img class="point" src="assets/x.gif" alt="" title="">';
	echo LANGUI_RES_T1;
	echo '</h1>
<p></p>
<form method="post" action="resources.php?avid=';
	echo $this->villageId;
	echo '">
<table cellpadding="1" cellspacing="1" id="position" class="small_option">
	<thead>
		<tr><th colspan="2">';
	echo LANGUI_RES_T2;
	echo '</th></tr>
	</thead>
	<tbody>
		<tr>
			<th>';
	echo LANGUI_RES_T3;
	echo '</th>
			<td>';
	echo $this->villageName;
	echo '</td>
		</tr>
		<tr>
			<th>';
	echo LANGUI_RES_T4;
	echo '</th>
			<td>';
	echo $this->playerName;
	echo '</td>
		</tr>
	</tbody>
</table><p></p>

<table cellpadding="1" cellspacing="1" id="rights" class="small_option">
	<thead>
		<tr><th>';
	echo LANGUI_RES_T5;
	echo '</th><th>';
	echo LANGUI_RES_T6;
	echo '</th><th>';
	echo LANGUI_RES_T7;
	echo '</th></tr>
	</thead>
	<tbody>
		<tr>
			<td class="sel"><img src="assets/x.gif" class="r1" alt="';
	echo item_title_1;
	echo '" title="';
	echo item_title_1;
	echo '" /> ';
	echo item_title_1;
	echo '</td>
			<td class="sel">';
	echo $this->resources[1]['store_max_limit'];
	echo '</td>
			<td><input class="name text" type="text" name="r1" value="';
	echo $this->resources[1]['current_value'];
	echo '" maxlength="20"></td>
		</tr>
		<tr>
			<td class="sel"><img src="assets/x.gif" class="r2" alt="';
	echo item_title_2;
	echo '" title="';
	echo item_title_2;
	echo '" /> ';
	echo item_title_2;
	echo '</td>
			<td class="sel">';
	echo $this->resources[2]['store_max_limit'];
	echo '</td>
			<td><input class="name text" type="text" name="r2" value="';
	echo $this->resources[2]['current_value'];
	echo '" maxlength="20"></td>
		</tr>
		<tr>
			<td class="sel"><img src="assets/x.gif" class="r3" alt="';
	echo item_title_3;
	echo '" title="';
	echo item_title_3;
	echo '" /> ';
	echo item_title_3;
	echo '</td>
			<td class="sel">';
	echo $this->resources[3]['store_max_limit'];
	echo '</td>
			<td><input class="name text" type="text" name="r3" value="';
	echo $this->resources[3]['current_value'];
	echo '" maxlength="20"></td>
		</tr>
		<tr>
			<td class="sel"><img src="assets/x.gif" class="r4" alt="';
	echo item_title_4;
	echo '" title="';
	echo item_title_4;
	echo '" /> ';
	echo item_title_4;
	echo '</td>
			<td class="sel">';
	echo $this->resources[4]['store_max_limit'];
	echo '</td>
			<td><input class="name text" type="text" name="r4" value="';
	echo $this->resources[4]['current_value'];
	echo '" maxlength="20"></td>
		</tr>
	</tbody>
</table>

<p><input type="image" value="ok" name="s1" id="btn_save" class="dynamic_img" src="assets/x.gif" alt="';
	echo text_save_lang;
	echo '"></p>
</form>
';

	if ($this->isPost()) {
		echo '<p class="error">';
		echo $this->msgText;
		echo '</p>';
	}

?>


