<?php
	echo '﻿';
	require_once( LANG_UI_PATH . 'training.php' );
	echo '<link rel=stylesheet type="text/css" href="assets/un_main2_';
	echo $this->appConfig['system']['lang'];
	echo '.css';
	echo $this->getAssetVersion();
	echo '"/>
<br/><br/>
<div id="lmid1"> 
		<div id="lmid2"><div class="headline"><h1>';
	echo LANGUI_TRAINING_T23;
	echo '</h1></div>

';

	if (!isset( $_GET['t'] )) {
		echo '<div class="wholebox"><h2>';
		echo LANGUI_TRAINING_T24;
		echo '</h2></div>
<div class="wholebox">
	<table id="tut_img"><tr>
	<td><img src="assets/default/img/tut/dorf_klein.jpg"  width="200" height="170" alt=""><br>';
		echo LANGUI_TRAINING_T1;
		echo '</td>
	<td><img src="assets/default/img/tut/dorf_gross.jpg"  width="200" height="170" alt=""><br>';
		echo LANGUI_TRAINING_T2;
		echo '</td>
	</tr></table>
	<table id="tut_txt"><tr>
	<td colspan="2"><br>';
		echo LANGUI_TRAINING_T3;
		echo '</td>
	</tr></table>
</div>
<div class="wholebox">
	<div id="tut_left"><a href="index.php">&laquo; ';
		echo LANGUI_TRAINING_T4;
		echo '</a></div>
	<div id="tut_right"><a href="training.php?t=1">';
		echo LANGUI_TRAINING_T5;
		echo ' &raquo;</a></div>
</div>

';
	} 
else {
		if ($_GET['t'] == 1) {
			echo '<div class="wholebox"><h2>';
			echo LANGUI_TRAINING_T25;
			echo '</h2></div>
<div class="wholebox">
	<table id="tut_img"><tr>
		<td><img src="assets/default/img/tut/rohstofffeld.gif" width="200" height="183" alt=""><br>';
			echo LANGUI_TRAINING_T6;
			echo '</td>
		<td><img src="assets/default/img/tut/rohstofffeld2.gif" width="200" height="183" alt=""><br>';
			echo LANGUI_TRAINING_T7;
			echo '</td>
	</tr></table>
	<table id="tut_txt"><tr>
		<td colspan="2"><br>';
			echo LANGUI_TRAINING_T8;
			echo '</td>
	</tr></table>
</div>
<div class="wholebox">
	<div id="tut_left"><a href="training.php">&laquo; ';
			echo LANGUI_TRAINING_T4;
			echo '</a></div>
	<div id="tut_right"><a href="training.php?t=2">';
			echo LANGUI_TRAINING_T5;
			echo ' &raquo;</a></div>
</div>

';
		} 
else {
			if ($_GET['t'] == 2) {
				echo '<div class="wholebox"><h2>';
				echo LANGUI_TRAINING_T26;
				echo '</h2></div>
<div class="wholebox">
	<table id="tut_img"><tr>
		<td><img src="assets/default/img/tut/dorfzentrum1.gif" width="200" height="183" alt=""><br>';
				echo LANGUI_TRAINING_T9;
				echo '</td>
		<td><img src="assets/default/img/tut/dorfzentrum2.gif" width="200" height="183" alt=""><br>';
				echo LANGUI_TRAINING_T10;
				echo '</td>
	</tr></table>
	<table id="tut_txt"><tr>
		<td colspan="2"><br>';
				echo LANGUI_TRAINING_T11;
				echo '</td>
	</tr></table>
</div>
<div class="wholebox">
	<div id="tut_left"><a href="training.php?t=1">&laquo; ';
				echo LANGUI_TRAINING_T4;
				echo '</a></div>
	<div id="tut_right"><a href="training.php?t=3">';
				echo LANGUI_TRAINING_T5;
				echo ' &raquo;</a></div>
</div>

';
			} 
else {
				if ($_GET['t'] == 3) {
					echo '<div class="wholebox"><h2>';
					echo LANGUI_TRAINING_T27;
					echo '</h2></div>
<div class="wholebox">
	<table id="tut_img"><tr>
		<td><img src="assets/default/img/tut/karte.jpg" width="468" height="200" alt=""><br>';
					echo LANGUI_TRAINING_T12;
					echo '</td>
	</tr></table>
	<table id="tut_txt"><tr>
		<td colspan="2">';
					echo LANGUI_TRAINING_T13;
					echo '</td>
	</tr></table>
</div>
<div class="wholebox">
	<div id="tut_left"><a href="training.php?t=2">&laquo; ';
					echo LANGUI_TRAINING_T4;
					echo '</a></div>
	<div id="tut_right"><a href="training.php?t=4">';
					echo LANGUI_TRAINING_T5;
					echo ' &raquo;</a></div>
</div>

';
				} 
else {
					if ($_GET['t'] == 4) {
						echo '<div class="wholebox"><h2>';
						echo LANGUI_TRAINING_T28;
						echo '</h2></div>
<div class="wholebox">
	<table id="tut_img" style="height:40px;"><tr>
		<td colspan="2"><img src="assets/default/img/tut/navi.jpg" width="468" height="100" alt=""><br>';
						echo LANGUI_TRAINING_T14;
						echo '</td>
	</tr></table>
	<table id="tut_txt"><tr>
		<td colspan="2">
			<ol start="1" type="1" class="f10">
				<li>';
						echo LANGUI_TRAINING_T15;
						echo '</li> 
				<li>';
						echo LANGUI_TRAINING_T16;
						echo '</li> 
				<li>';
						echo LANGUI_TRAINING_T17;
						echo '</li> 
				<li>';
						echo LANGUI_TRAINING_T18;
						echo '</li> 
				<li>';
						echo LANGUI_TRAINING_T19;
						echo '</li> 
				<li>';
						echo LANGUI_TRAINING_T20;
						echo '</li>
			</ol>
			';
						echo LANGUI_TRAINING_T21;
						echo '</td>
	</tr></table>
</div>
<div class="wholebox">
	<div id="tut_left"><a href="training.php?t=3">&laquo; ';
						echo LANGUI_TRAINING_T4;
						echo '</a></div>
	<div id="tut_right"><a href="register.php"  id="link2">';
						echo LANGUI_TRAINING_T22;
						echo ' &raquo;</a></div>
</div>
';
					}
				}
			}
		}
	}

	echo '
<div style="clear:both;"></div>
</div></div>';
?>


