<?php

	require_once( LANG_UI_PATH . 'village1.php' );
	echo '<h1>';
	echo $this->data['village_name'];
	echo '<br>';

	if ($this->data['allegiance_percent'] < 100) {
		echo '<div id="loyality" class="';
		echo ($this->data['allegiance_percent'] <= 60 ? 're' : 'gr');
		echo '">';
		echo LANGUI_VIL1_T1;
		echo ' ';
		echo $this->data['allegiance_percent'];
		echo '%</div>';
	}

	echo '</h1><map name="rx" id="rx"><area href="build.php?id=1" coords="101,33,28" shape="circle" ';
	echo $this->getBuildingTitle( 1 );
	echo '><area href="build.php?id=2" coords="165,32,28" shape="circle" ';
	echo $this->getBuildingTitle( 2 );
	echo '><area href="build.php?id=3" coords="224,46,28" shape="circle" ';
	echo $this->getBuildingTitle( 3 );
	echo '><area href="build.php?id=4" coords="46,63,28" shape="circle" ';
	echo $this->getBuildingTitle( 4 );
	echo '><area href="build.php?id=5" coords="138,74,28" shape="circle" ';
	echo $this->getBuildingTitle( 5 );
	echo '><area href="build.php?id=6" coords="203,94,28" shape="circle" ';
	echo $this->getBuildingTitle( 6 );
	echo '><area href="build.php?id=7" coords="262,86,28" shape="circle" ';
	echo $this->getBuildingTitle( 7 );
	echo '><area href="build.php?id=8" coords="31,117,28" shape="circle" ';
	echo $this->getBuildingTitle( 8 );
	echo '><area href="build.php?id=9" coords="83,110,28" shape="circle" ';
	echo $this->getBuildingTitle( 9 );
	echo '><area href="build.php?id=10" coords="214,142,28" shape="circle" ';
	echo $this->getBuildingTitle( 10 );
	echo '><area href="build.php?id=11" coords="269,146,28" shape="circle" ';
	echo $this->getBuildingTitle( 11 );
	echo '><area href="build.php?id=12" coords="42,171,28" shape="circle" ';
	echo $this->getBuildingTitle( 12 );
	echo '><area href="build.php?id=13" coords="93,164,28" shape="circle" ';
	echo $this->getBuildingTitle( 13 );
	echo '><area href="build.php?id=14" coords="160,184,28" shape="circle" ';
	echo $this->getBuildingTitle( 14 );
	echo '><area href="build.php?id=15" coords="239,199,28" shape="circle" ';
	echo $this->getBuildingTitle( 15 );
	echo '><area href="build.php?id=16" coords="87,217,28" shape="circle" ';
	echo $this->getBuildingTitle( 16 );
	echo '><area href="build.php?id=17" coords="140,231,28" shape="circle" ';
	echo $this->getBuildingTitle( 17 );
	echo '><area href="build.php?id=18" coords="190,232,28" shape="circle" ';
	echo $this->getBuildingTitle( 18 );
	echo '><area href="village2.php" coords="144,131,36" shape="circle" title="';
	echo LANGUI_VIL1_T2;
	echo '" alt="';
	echo LANGUI_VIL1_T2;
	echo '"></map><div id="village_map" class="f';
	echo $this->data['field_maps_id'];
	echo '">';
	foreach ($this->buildings as $id => $build) {
		if (19 <= $id) {
			break;
		}


		if (0 < $build['level']) {
			echo '<img src="assets/x.gif" class="reslevel rf' . $id . ' level' . $build['level'] . '" alt="' . $this->getBuildingName( $id ) . '">';
			continue;
		}
	}

	echo '<img id="resfeld" usemap="#rx" src="assets/x.gif" alt=""></div><div id="map_details">	';

	if (0 < $this->queueModel->tasksInQueue['war_troops_summary']['total_number']) {
		echo '	<table id="movements" cellpadding="1" cellspacing="1">		<thead><tr><th colspan="3">';
		echo LANGUI_VIL1_T3;
		echo ':</th></tr></thead>		<tbody>			';
		$war = $this->queueModel->tasksInQueue['war_troops_summary']['to_me']['attacks'];

		if (0 < $war['number']) {
			echo '			<tr>				<td class="typ"><a href="build.php?id=39"><img src="assets/x.gif" class="att1" alt="';
			echo LANGUI_VIL1_T4;
			echo '" title="';
			echo LANGUI_VIL1_T4;
			echo '"></a>';
			echo '<s';
			echo 'pan class="a1">»</span></td>				<td><div class="mov">';
			echo '<s';
			echo 'pan class="a1">';
			echo $war['number'];
			echo '&nbsp;';
			echo LANGUI_VIL1_T5;
			echo '</span></div><div class="dur_r">';
			echo text_in_lang;
			echo '&nbsp;';
			echo '<s';
			echo 'pan id="timer1">';
			echo WebHelper::secondstostring( $war['min_time'] );
			echo '</span>&nbsp;';
			echo time_hour_lang;
			echo '</div></td>			</tr>			';
		}

		echo '			';
		$war = $this->queueModel->tasksInQueue['war_troops_summary']['to_me']['reinforce'];

		if (0 < $war['number']) {
			echo '			<tr>				<td class="typ"><a href="build.php?id=39"><img src="assets/x.gif" class="def1" alt="';
			echo LANGUI_VIL1_T6;
			echo '" title="';
			echo LANGUI_VIL1_T6;
			echo '"></a>';
			echo '<s';
			echo 'pan class="d1">»</span></td>				<td><div class="mov">';
			echo '<s';
			echo 'pan class="d1">';
			echo $war['number'];
			echo '&nbsp;';
			echo LANGUI_VIL1_T7;
			echo '</span></div><div class="dur_r">';
			echo text_in_lang;
			echo '&nbsp;';
			echo '<s';
			echo 'pan id="timer1">';
			echo WebHelper::secondstostring( $war['min_time'] );
			echo '</span>&nbsp;';
			echo time_hour_lang;
			echo '</div></td>			</tr>			';
		}

		echo '			';
		$war = $this->queueModel->tasksInQueue['war_troops_summary']['from_me']['attacks'];

		if (0 < $war['number']) {
			echo '			<tr>				<td class="typ"><a href="build.php?id=39"><img src="assets/x.gif" class="att2" alt="';
			echo LANGUI_VIL1_T8;
			echo '" title="';
			echo LANGUI_VIL1_T8;
			echo '"></a>';
			echo '<s';
			echo 'pan class="a2">«</span></td>				<td><div class="mov">';
			echo '<s';
			echo 'pan class="a2">';
			echo $war['number'];
			echo '&nbsp;';
			echo LANGUI_VIL1_T5;
			echo '</span></div><div class="dur_r">';
			echo text_in_lang;
			echo '&nbsp;';
			echo '<s';
			echo 'pan id="timer1">';
			echo WebHelper::secondstostring( $war['min_time'] );
			echo '</span>&nbsp;';
			echo time_hour_lang;
			echo '</div></td>			</tr>			';
		}

		echo '			';
		$war = $this->queueModel->tasksInQueue['war_troops_summary']['from_me']['reinforce'];

		if (0 < $war['number']) {
			echo '			<tr>				<td class="typ"><a href="build.php?id=39"><img src="assets/x.gif" class="def2" alt="';
			echo LANGUI_VIL1_T9;
			echo '" title="';
			echo LANGUI_VIL1_T9;
			echo '"></a>';
			echo '<s';
			echo 'pan class="d2">«</span></td>				<td><div class="mov">';
			echo '<s';
			echo 'pan class="d2">';
			echo $war['number'];
			echo '&nbsp;';
			echo LANGUI_VIL1_T7;
			echo '</span></div><div class="dur_r">';
			echo text_in_lang;
			echo '&nbsp;';
			echo '<s';
			echo 'pan id="timer1">';
			echo WebHelper::secondstostring( $war['min_time'] );
			echo '</span>&nbsp;';
			echo time_hour_lang;
			echo '</div></td>			</tr>			';
		}

		echo '						';
		$war = $this->queueModel->tasksInQueue['war_troops_summary']['to_my_oasis']['attacks'];

		if (0 < $war['number']) {
			echo '			<tr>				<td class="typ"><a href="build.php?id=39"><img src="assets/x.gif" class="att3" alt="';
			echo LANGUI_VIL1_T10;
			echo '" title="';
			echo LANGUI_VIL1_T10;
			echo '"></a>';
			echo '<s';
			echo 'pan class="a3">»</span></td>				<td><div class="mov">';
			echo '<s';
			echo 'pan class="a3">';
			echo $war['number'];
			echo '&nbsp;';
			echo LANGUI_VIL1_T5;
			echo '</span></div><div class="dur_r">';
			echo text_in_lang;
			echo '&nbsp;';
			echo '<s';
			echo 'pan id="timer1">';
			echo WebHelper::secondstostring( $war['min_time'] );
			echo '</span>&nbsp;';
			echo time_hour_lang;
			echo '</div></td>			</tr>			';
		}

		echo '			';
		$war = $this->queueModel->tasksInQueue['war_troops_summary']['to_my_oasis']['reinforce'];

		if (0 < $war['number']) {
			echo '			<tr>				<td class="typ"><a href="build.php?id=39"><img src="assets/x.gif" class="def3" alt="';
			echo LANGUI_VIL1_T11;
			echo '" title="';
			echo LANGUI_VIL1_T11;
			echo '"></a>';
			echo '<s';
			echo 'pan class="d3">»</span></td>				<td><div class="mov">';
			echo '<s';
			echo 'pan class="d3">';
			echo $war['number'];
			echo '&nbsp;';
			echo LANGUI_VIL1_T7;
			echo '</span></div><div class="dur_r">';
			echo text_in_lang;
			echo '&nbsp;';
			echo '<s';
			echo 'pan id="timer1">';
			echo WebHelper::secondstostring( $war['min_time'] );
			echo '</span>&nbsp;';
			echo time_hour_lang;
			echo '</div></td>			</tr>			';
		}

		echo '		</tbody>	</table>	';
	}

	echo '	<table id="production" cellpadding="1" cellspacing="1">		<thead>			<tr><th colspan="4">';
	echo LANGUI_VIL1_T12;
	echo ':</th></tr>		</thead>		<tbody>				<tr>				<td class="ico"><img class="r1" src="assets/x.gif" alt="';
	echo item_title_1;
	echo '" title="';
	echo item_title_1;
	echo '"></td>				<td class="res">';
	echo item_title_1;
	echo ':</td>				<td class="num">';
	echo $this->resources[1]['calc_prod_rate'];
	echo '</td>				<td class="per">';
	echo LANGUI_VIL1_T13;
	echo '</td>			</tr>			<tr>				<td class="ico"><img class="r2" src="assets/x.gif" alt="';
	echo item_title_2;
	echo '" title="';
	echo item_title_2;
	echo '"></td>				<td class="res">';
	echo item_title_2;
	echo ':</td>				<td class="num">';
	echo $this->resources[2]['calc_prod_rate'];
	echo '</td>				<td class="per">';
	echo LANGUI_VIL1_T13;
	echo '</td>			</tr>							<tr>				<td class="ico"><img class="r3" src="assets/x.gif" alt="';
	echo item_title_3;
	echo '" title="';
	echo item_title_3;
	echo '"></td>				<td class="res">';
	echo item_title_3;
	echo ':</td>				<td class="num">';
	echo $this->resources[3]['calc_prod_rate'];
	echo '</td>				<td class="per">';
	echo LANGUI_VIL1_T13;
	echo '</td>			</tr>				<tr>				<td class="ico"><img class="r4" src="assets/x.gif" alt="';
	echo item_title_4;
	echo '" title="';
	echo item_title_4;
	echo '"></td>				<td class="res">';
	echo item_title_4;
	echo ':</td>				<td class="num">';
	echo $this->resources[4]['calc_prod_rate'];
	echo '</td>				<td class="per">';
	echo LANGUI_VIL1_T13;
	echo '</td>			</tr>		</tbody>		</table>	<table id="troops" cellpadding="1" cellspacing="1">		<thead>			<tr><th colspan="3">';
	echo LANGUI_VIL1_T14;
	echo ':</th></tr>		</thead>		<tbody>';

	if (( $this->heroCount == 0 && sizeof( $this->troops ) == 0 )) {
		echo '			<tr><td>';
		echo LANGUI_VIL1_T15;
		echo '</td></tr>';
	} 
else {
		if (0 < $this->heroCount) {
			echo '			<tr>				<td class="ico"><a href="build.php?id=39"><img class="unit uhero" src="assets/x.gif" alt="';
			echo troop_hero;
			echo '" title="';
			echo troop_hero;
			echo '"></a></td>				<td class="num">';
			echo $this->heroCount;
			echo '</td>				<td class="un">';
			echo troop_hero;
			echo '</td>			</tr>';
		}

		foreach ($this->troops as $k => $v) {
			$troopName = htmlspecialchars( constant( 'troop_' . $k ) );
			echo '			<tr>				<td class="ico"><a href="build.php?id=39"><img class="unit u';
			echo $k;
			echo '" src="assets/x.gif" alt="';
			echo $troopName;
			echo '" title="';
			echo $troopName;
			echo '"></a></td>				<td class="num">';
			echo $v;
			echo '</td>				<td class="un">';
			echo $troopName;
			echo '</td>			</tr>';
		}
	}

	echo '		</tbody>	</table></div>';

	if (isset( $this->queueModel->tasksInQueue[QS_BUILD_CREATEUPGRADE] )) {
		echo '<table cellpadding="1" cellspacing="1" id="building_contract">	<thead>		<tr>			<th colspan="3">				';
		echo LANGUI_VIL1_T16;
		echo ': 				';

		if (( !$this->data['is_special_village'] && $this->gameMetadata['plusTable'][5]['cost'] <= $this->data['gold_num'] )) {
			echo '				<a href="village1.php?bfs&k=';
			echo $this->data['update_key'];
			echo '" title="';
			echo LANGUI_VIL1_T18;
			echo '">				<img class="clock" alt="';
			echo LANGUI_VIL1_T18;
			echo '" src="assets/x.gif"></a>				';
		}

		echo '			</th>		</tr>	</thead>	<tbody>		';
		$tmpBuilding = array();
		foreach ($this->queueModel->tasksInQueue[QS_BUILD_CREATEUPGRADE] as $qtask) {
			$index = $qtask['proc_params'];
			$itemId = $qtask['building_id'];

			if (!isset( $tmpBuilding[$index] )) {
				$tmpBuilding[$index] = 0;
			}

			++$tmpBuilding[$index];
			$level = $this->buildings[$index]['level'] + $tmpBuilding[$index];
			echo '		<tr>			<td class="ico"><a href="?id=';
			echo $qtask['id'];
			echo '&d&k=';
			echo $this->data['update_key'];
			echo '"><img src="assets/x.gif" class="del" title="';
			echo LANGUI_VIL1_T17;
			echo '" alt="';
			echo LANGUI_VIL1_T17;
			echo '"></a></td>			<td>';
			echo constant( 'item_' . $itemId );
			echo ' (';
			echo level_lang;
			echo ' ';
			echo $level;
			echo ')</td>			<td>';
			echo time_remain_lang;
			echo ' ';
			echo '<s';
			echo 'pan id="timer1">';
			echo WebHelper::secondstostring( $qtask['remainingSeconds'] );
			echo '</span> ';
			echo time_hour_lang;
			echo '</td>		</tr>		';
		}

		unset( $tmpBuilding );
		echo '	</tbody></table>';
	}

?>


