<?php
	// hotfix for non static methods adding it here since there is multiple places where static method was called
	// easier to call new class once and call the function from it once we need it, than create new class all the time right?
	$webhelper_client = new WebHelper();
	require_once( LANG_UI_PATH . 'custbuilds.php' );
	echo '<p></p><p></p>
<table cellpadding="1" cellspacing="1" class="build_details">
	<thead>
		<tr>
			<td>';
	echo ($this->troopsUpgradeType == QS_TROOP_UPGRADE_ATTACK ? item_12 : item_13);
	echo '</td>
			<td>';
	echo LANGUI_CUSTBU_BLK_t1;
	echo '</td>
		</tr>
	</thead>
	<tbody>
		';
	$_ac = 0;
	$buildingMetadata = $this->gameMetadata['items'][$this->buildProperties['building']['item_id']]['troop_upgrades'];
	foreach ($this->troopsUpgrade as $tid => $ulevel) {
		++$_ac;
		$lvl = $buildingMetadata[$tid][$ulevel];
		$lvlTime = intval( $lvl['time_consume'] / $this->gameSpeed * ( 10 / ( $this->buildProperties['building']['level'] + 9 ) ) );
		echo '		<tr>
			<td class="desc">
				<div class="tit"><img class="unit u';
		echo $tid;
		echo '" src="assets/x.gif" alt="';
		echo constant( 'troop_' . $tid );
		echo '" title="';
		echo constant( 'troop_' . $tid );
		echo '"><a href="#" onclick="return showManual(3,';
		echo $tid;
		echo ');">';
		echo constant( 'troop_' . $tid );
		echo '</a> ';
		echo '<s';
		echo 'pan class="info">(';
		echo level_lang2;
		echo ' ';
		echo $ulevel;
		echo ')</span></div>
				<div class="details">
					<img class="r1" src="assets/x.gif" alt="';
		echo item_title_1;
		echo '" title="';
		echo item_title_1;
		echo '">';
		echo '<s';
		echo 'pan class="little_res">';
		echo $lvl['resources'][1];
		echo '</span>|<img class="r2" src="assets/x.gif" alt="';
		echo item_title_2;
		echo '" title="';
		echo item_title_2;
		echo '">';
		echo '<s';
		echo 'pan class="little_res">';
		echo $lvl['resources'][2];
		echo '</span>|<img class="r3" src="assets/x.gif" alt="';
		echo item_title_3;
		echo '" title="';
		echo item_title_3;
		echo '">';
		echo '<s';
		echo 'pan class="little_res">';
		echo $lvl['resources'][3];
		echo '</span>|<img class="r4" src="assets/x.gif" alt="';
		echo item_title_4;
		echo '" title="';
		echo item_title_4;
		echo '">';
		echo '<s';
		echo 'pan class="little_res">';
		echo $lvl['resources'][4];
		echo '</span>|<img class="clock" src="assets/x.gif" alt="';
		echo text_period_lang;
		echo '" title="';
		echo text_period_lang;
		echo '">';
		echo $webhelper_client->secondstostring( $lvlTime );
		echo $this->getResourceGoldExchange( $lvl['resources'], 0, $this->buildingIndex );
		echo '				</div>
				';
		echo $this->getActionText2( $lvl['resources'] );
		echo '			</td>
			<td class="act">';
		echo $this->getActionText4( $lvl['resources'], 'a=' . $tid, LANGUI_CUSTBU_BLK_t4, $this->troopsUpgradeType, $this->buildProperties['building']['level'], $ulevel );
		echo '</td>
		</tr>
		';
	}

	echo '		';

	if ($_ac == 0) {
		echo '		<tr><td colspan="2">';
		echo '<s';
		echo 'pan class="none">';
		echo LANGUI_CUSTBU_BLK_t2;
		echo '</span></td></tr>
		';
	}

	echo '	</tbody>
</table>
';

	if (isset( $this->queueModel->tasksInQueue[$this->troopsUpgradeType] )) {
		list( $tid, $ulevel ) = explode( ' ', $this->queueModel->tasksInQueue[$this->troopsUpgradeType][0]['proc_params'] );
		echo '<table cellpadding="1" cellspacing="1" class="under_progress">
	<thead>
		<tr>
			<td>';
		echo LANGUI_CUSTBU_BLK_t3;
		echo '</td>
			<td>';
		echo text_period_lang;
		echo '</td>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td class="desc"><img class="unit u';
		echo $tid;
		echo '" src="assets/x.gif" alt="';
		echo constant( 'troop_' . $tid );
		echo '" title="';
		echo constant( 'troop_' . $tid );
		echo '">';
		echo constant( 'troop_' . $tid );
		echo '  ';
		echo '<s';
		echo 'pan class="info">(';
		echo level_lang2;
		echo ' ';
		echo $ulevel;
		echo ')</span></td>
			<td class="dur">';
		echo '<s';
		echo 'pan id="timer1">';
		echo $webhelper_client->secondstostring( $this->queueModel->tasksInQueue[$this->troopsUpgradeType][0]['remainingSeconds'] );
		echo '</span></td>
		</tr>
		<tr class="next"><td colspan="2">&nbsp;</td></tr>
	</tbody>
</table>
';
	}

?>

