<?php
	// hotfix for non static methods adding it here since there is multiple places where static method was called
	// easier to call new class once and call the function from it once we need it, than create new class all the time right?
	$webhelper_client = new WebHelper();
	
	require_once( LANG_UI_PATH . 'custbuilds.php' );
	echo '<div id="textmenu">
   <a href="build.php?id=';
	echo $this->buildingIndex;
	echo '"';

	if ($this->selectedTabIndex == 0) {
		echo ' class="selected"';
	}

	echo '>';
	echo LANGUI_CUSTBU_HRO_p1;
	echo '</a>
 | <a href="build.php?id=';
	echo $this->buildingIndex;
	echo '&t=1"';

	if ($this->selectedTabIndex == 1) {
		echo ' class="selected"';
	}

	echo '>';
	echo LANGUI_CUSTBU_HRO_p2;
	echo '</a>
</div>
';

	if ($this->selectedTabIndex == 0) {
		if (!$this->hasHero) {
			if (!isset( $this->queueModel->tasksInQueue[$this->troopsUpgradeType] )) {
				echo '<table class="build_details" cellpadding="1" cellspacing="1">
	<thead>
		<tr>
			<td colspan="2">';
				echo LANGUI_CUSTBU_HRO_p1_t1;
				echo '</td>
		</tr>
	</thead>
	<tbody>
		';
				$_c = 0;
				foreach ($this->troops as $tid => $tnum) {
					if ($tnum <= 0) {
						continue;
					}

					++$_c;
					$troopMetadata = $this->gameMetadata['troops'][$tid];
					$lvlTime = intval( $troopMetadata['training_time_consume'] / $this->gameSpeed * ( 10 / ( $this->buildProperties['building']['level'] + 9 ) ) ) * 12;
					$res = array( '1' => $troopMetadata['training_resources'][1] * 2, '2' => $troopMetadata['training_resources'][2] * 2, '3' => $troopMetadata['training_resources'][3] * 2, '4' => $troopMetadata['training_resources'][4] * 2 );
					echo '		<tr>
			<td class="desc">
				<div class="tit">
					<img class="unit u';
					echo $tid;
					echo '" src="assets/x.gif" alt="';
					echo constant( 'troop_' . $tid );
					echo '" title="';
					echo constant( 'troop_' . $tid );
					echo '"> <a href="#" onclick="return showManual(3,';
					echo $tid;
					echo ');">';
					echo constant( 'troop_' . $tid );
					echo '</a>
				</div>
				<div class="details">
					<img class="r1" src="assets/x.gif" alt="';
					echo item_title_1;
					echo '" title="';
					echo item_title_1;
					echo '">';
					echo '<s';
					echo 'pan class="little_res">';
					echo $res[1];
					echo '</span>|<img class="r2" src="assets/x.gif" alt="';
					echo item_title_2;
					echo '" title="';
					echo item_title_2;
					echo '">';
					echo $res[2];
					echo '|<img class="r3" src="assets/x.gif" alt="';
					echo item_title_3;
					echo '" title="';
					echo item_title_3;
					echo '">';
					echo $res[3];
					echo '|<img class="r4" src="assets/x.gif" alt="';
					echo item_title_4;
					echo '" title="';
					echo item_title_4;
					echo '">';
					echo $res[4];
					echo '|<img class="clock" src="assets/x.gif" alt="';
					echo text_period_lang;
					echo '" title="';
					echo text_period_lang;
					echo '">';
					echo $webhelper_client->secondstostring( $lvlTime );
					echo $this->getResourceGoldExchange( $res, 0, $this->buildingIndex );
					echo '				</div>
				';
					echo $this->getActionText2( $res );
					echo '			</td>
			<td class="act">';
					echo $this->getActionText3( $res, 'a=' . $tid, LANGUI_CUSTBU_HRO_p1_t7, $this->troopsUpgradeType );
					echo '</td>
		</tr>
		';
				}


				if ($_c == 0) {
					echo '		<tr><td colspan="2" class="none">';
					echo LANGUI_CUSTBU_HRO_p1_t2;
					echo '</td></tr>
		';
				}

				echo '	</tbody>
</table>
';
				return 1;
			}

			echo '<p>';
			echo LANGUI_CUSTBU_HRO_p1_t3;
			echo ' <b>';
			echo '<s';
			echo 'pan id="timer1">';
			echo $webhelper_client->secondstostring( $this->queueModel->tasksInQueue[$this->troopsUpgradeType][0]['remainingSeconds'] );
			echo '</span></b> ';
			echo time_hour_lang;
			return 1;
		}

		echo '<form method="post" name="snd" action="build.php?id=';
		echo $this->buildingIndex;
		echo '">
<table id="distribution" cellpadding="1" cellspacing="1">
	<thead>
		<tr>
			<th colspan="2">';
		echo $this->data['hero_name'];
		echo ' ';
		echo level_lang;
		echo ' ';
		echo $this->data['hero_level'];
		echo ' ';
		echo '<s';
		echo 'pan class="info">(';
		echo constant( 'troop_' . $this->data['hero_troop_id'] );
		echo ')</span></th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<th>';
		echo LANGUI_CUSTBU_HRO_p1_t4;
		echo ':</th>
			<td class="val">';
		echo $this->data['hero_points'];
		echo '</td>
		</tr>
		<tr>
			<th>';
		echo LANGUI_CUSTBU_HRO_p1_t5;
		echo ':</th>
			<td class="val"><input tabindex="6" type="text" name="hname" value="';
		echo htmlspecialchars( $this->data['hero_name'] );
		echo '" maxlength="20" class="text"></td>
		</tr>
	</tbody>
</table>
<p class="btn"><input type="image" value="" tabindex="9" name="s1" id="btn_save" class="dynamic_img" src="assets/x.gif" alt="';
		echo LANGUI_CUSTBU_HRO_p1_t6;
		echo '"></p>
</form>
';
		return 1;
	}


	if ($this->selectedTabIndex == 1) {
		echo '<table id="oases" cellpadding="1" cellspacing="1">
	<thead>
		<tr><th colspan="5">';
		echo LANGUI_CUSTBU_HRO_p2_t1;
		echo '</th></tr>
		<tr>
			<td>&nbsp;</td>
			<td>';
		echo LANGUI_CUSTBU_HRO_p2_t2;
		echo '</td>
			<td>';
		echo LANGUI_CUSTBU_HRO_p2_t3;
		echo '</td>
			<td>';
		echo LANGUI_CUSTBU_HRO_p2_t4;
		echo '</td>
			<td>';
		echo LANGUI_CUSTBU_HRO_p2_t5;
		echo '</td>
		</tr>
	</thead>
	<tbody>
		';
		foreach ($this->villageOases as $oasis) {
			echo '		<tr>
			<td>
				';

			if (!isset( $this->queueModel->tasksInQueue[QS_LEAVEOASIS][$oasis['id']] )) {
				echo '				<a href="build.php?id=';
				echo $this->buildingIndex;
				echo '&t=1&a=';
				echo $oasis['id'];
				echo '&k=';
				echo $this->data['update_key'];
				echo '"><img class="del" src="assets/x.gif" alt="';
				echo LANGUI_CUSTBU_HRO_p2_t6;
				echo '" title="';
				echo LANGUI_CUSTBU_HRO_p2_t6;
				echo '"></a>
				';
			}

			echo '			</td>
			<td class="nam"><a href="village3.php?id=';
			echo $oasis['id'];
			echo '">';
			echo LANGUI_CUSTBU_HRO_p2_t7;
			echo '</a></td>
			<td class="aligned_coords"><div class="cox">(';
			echo $oasis['rel_x'];
			echo '</div><div class="pi">|</div><div class="coy">';
			echo $oasis['rel_y'];
			echo ')</div></td>
			<td class="zp">';
			echo $oasis['allegiance_percent'];
			echo '%</td>
			<td class="res">
';
			$oid = $this->setupMetadata['oasis'][$oasis['image_num']];
			$str = '';
			foreach ($oid as $k => $v) {
				if ($str != '') {
					$str .= PHP_EOL . ' ' . text_and_lang . ' ';
				}

				$str .= sprintf( '<img class="r%s" src="assets/x.gif" alt="%s" title="%s">+%s%%', $k, constant( 'item_title_' . $k ), constant( 'item_title_' . $k ), $v );
			}

			echo $str;
			echo '</td>
		</tr>
		';
		}

		echo '	</tbody>
</table><br/><br/>

';

		if (isset( $this->queueModel->tasksInQueue[QS_LEAVEOASIS] )) {
			echo '<h2>';
			echo LANGUI_CUSTBU_HRO_p2_t6;
			echo '</h2>
<table id="leave" cellpadding="1" cellspacing="1">
	<thead>
		<tr>
			<td>';
			echo LANGUI_CUSTBU_HRO_p2_t2;
			echo '</td>
			<td>';
			echo LANGUI_CUSTBU_HRO_p2_t3;
			echo '</td>
			<td>';
			echo text_period_lang;
			echo '</td>
		</tr>
	</thead>
	<tbody>
		';
			foreach ($this->queueModel->tasksInQueue[QS_LEAVEOASIS] as $oasisId => $qtArray) {
				$qt = $qtArray[0];
				$coordArray = explode( ' ', $qt['proc_params'] );
				echo '		<tr>
			<td class="nam">
				<a href="build.php?id=';
				echo $this->buildingIndex;
				echo '&t=1&qid=';
				echo $qt['id'];
				echo '"><img class="del" src="assets/x.gif" alt="';
				echo LANGUI_CUSTBU_HRO_p2_t8;
				echo '" title="';
				echo LANGUI_CUSTBU_HRO_p2_t8;
				echo '"></a>
				<a href="village3.php?id=';
				echo $oasisId;
				echo '">';
				echo LANGUI_CUSTBU_HRO_p2_t7;
				echo '</a>
			</td>
			<td class="aligned_coords"><div class="cox">(';
				echo $coordArray[0];
				echo '</div><div class="pi">|</div><div class="coy">';
				echo $coordArray[1];
				echo ')</div></td>
			<td class="dur">';
				echo '<s';
				echo 'pan id="timer1">';
				echo $webhelper_client->secondstostring( $qt['remainingSeconds'] );
				echo '</span></td>
		</tr>
		';
			}

			echo '	</tbody>
</table>
';
		}

		echo '<br/>
';
	}

?>

