<?php
	// hotfix for non static methods adding it here since there is multiple places where static method was called
	// easier to call new class once and call the function from it once we need it, than create new class all the time right?
	$webhelper_client = new WebHelper();

	require_once( LANG_UI_PATH . 'custbuilds.php' );
	echo '<h2>';
	echo LANGUI_CUSTBU_M_DROP;
	echo ':</h2>
<p>';
	echo LANGUI_CUSTBU_M_DROPDESC;
	echo '.</p>
';

	if (isset( $this->queueModel->tasksInQueue[QS_BUILD_DROP] )) {
		$qtask = $this->queueModel->tasksInQueue[QS_BUILD_DROP][0];
		echo '<table cellpadding="1" cellspacing="1" id="demolish">
	<tbody>
		<tr>
			<td><a href="build.php?id=';
		echo $this->buildingIndex;
		echo '&d&qid=';
		echo $qtask['id'];
		echo '&k=';
		echo $this->data['update_key'];
		echo '"><img class="del" src="assets/x.gif" title="';
		echo LANGUI_CUSTBU_M_CANCEL;
		echo '" alt="';
		echo LANGUI_CUSTBU_M_CANCEL;
		echo '"></a></td>
			<td>';
		echo constant( 'item_' . $qtask['building_id'] );
		echo ' (';
		echo level_lang;
		echo ' ';
		echo $this->buildings[$qtask['proc_params']]['level'];
		echo ')</td>
			<td>';
		echo time_remain_lang;
		echo ' ';
		echo '<s';
		echo 'pan id="timer1">';
		echo $webhelper_client->secondstostring( $qtask['remainingSeconds'] );
		echo '</span> ';
		echo time_hour_lang;
		echo '</td>
		</tr>
	</tbody>
</table>
';
		return 1;
	}

	echo '<div id="contract">
<form class="demolish_building" action="build.php?id=';
	echo $this->buildingIndex;
	echo '" method="post" style="display:inline">
	';
	echo '<s';
	echo 'elect name="drbid" class="dropdown">
		';
	$i = 19;
	$_c = sizeof( $this->buildings );

	while ($i < $_c) {
		echo '		<option value="';
		echo $i;
		echo '">';
		echo $i . '. ';

		if (0 < $this->buildings[$i]['item_id']) {
			echo constant( 'item_' . $this->buildings[$i]['item_id'] ) . ' ' . $this->buildings[$i]['level'];
		} 
else {
			echo LANGUI_CUSTBU_M_EMPTY;
		}

		echo '</option>
		';
		++$i;
	}

	echo '	</select>
	<input id="btn_demolish" name="ok" class="dynamic_img" type="image" src="assets/x.gif" alt="';
	echo LANGUI_CUSTBU_M_DROPBTN;
	echo '">
</form>
</div>
';
?>

