<?php

	require_once( LANG_UI_PATH . 'custbuilds.php' );
	echo '<p></p><p></p>

<div id="textmenu">
<a href="build.php?id=';
	echo $this->buildingIndex;
	echo '" class="selected">';
	echo LANGUI_CUSTBU_RP_p1;
	echo '</a>
 | <a href="v2v.php">';
	echo LANGUI_CUSTBU_RP_p2;
	echo '</a>
 | <a href="warsm.php">';
	echo LANGUI_CUSTBU_RP_p3;
	echo '</a>
</div>


';

	if (0 < sizeof( $this->rallyPointProperty['war_to_village'] )) {
		
		$m = new BuildModel();
		echo '<h4>';
		echo LANGUI_CUSTBU_RP_t1;
		echo '</h4>
';
		foreach ($this->rallyPointProperty['war_to_village'] as $taskTable) {
			$procType = $taskTable['proc_type'];
			$resources = NULL;
			$action1 = '';
			switch ($procType) {
				case QS_WAR_REINFORCE: {
					$_arr = explode( '|', $taskTable['proc_params'] );
					$troopsBack = $_arr[sizeof( $_arr ) - 1] == 1;
					$action1 = ($troopsBack ? LANGUI_CUSTBU_RP_t2 : LANGUI_CUSTBU_RP_t10);

					if (( $troopsBack && trim( $_arr[4] ) != '' )) {
						$resources = explode( ' ', $_arr[4] );
					}

					break;
				}

				case QS_WAR_ATTACK: {
					$action1 = LANGUI_CUSTBU_RP_t3;
					break;
				}

				case QS_WAR_ATTACK_PLUNDER: {
					$action1 = LANGUI_CUSTBU_RP_t4;
				}
			}

			$action1 .= ' ' . $this->data['village_name'];
			$action2 = '';
			$actionRow = $m->getVillageData2ById( intval( $taskTable['village_id'] ) );

			if (( $actionRow == NULL || intval( $actionRow['player_id'] ) != intval( $taskTable['player_id'] ) )) {
				$action2 .= '<span class="none">[?]</span>';
			} 
else {
				$action2 .= ($actionRow['tribe_id'] == 4 ? LANGUI_CUSTBU_RP_t5 : $actionRow['village_name']);
			}

			$_arr = explode( '|', $taskTable['proc_params'] );
			$troopsStr = explode( ',', $_arr[0] );
			$hasHero = FALSE;
			$troops = array();
			foreach ($troopsStr as $s) {
				list( $tid, $tnum ) = explode( ' ', $s );

				if ($tnum == 0 - 1) {
					$hasHero = TRUE;
					continue;
				}

				$troops[$tid] = $tnum;
			}

			$colspan = (( $hasHero && $procType == QS_WAR_REINFORCE ) ? 11 : 10);
			echo '<table class="troop_details" cellpadding="1" cellspacing="1">
	<thead>
		<tr>
			<td class="role">';

			if (( $actionRow != NULL && $actionRow['player_id'] == $taskTable['player_id'] )) {
				echo '<a href="village3.php?id=';
				echo $taskTable['village_id'];
				echo '">';
				echo $action2;
				echo '</a>';
			} 
else {
				echo $action2;
			}

			echo '</td>
			<td colspan="';
			echo $colspan;
			echo '"><a href="village3.php?id=';
			echo $taskTable['to_village_id'];
			echo '"><p>';
			echo $action1;
			echo '</p></a></td>
		</tr>
	</thead>
	<tbody class="units">
		<tr>
			<th>&nbsp;</th>
			';
			foreach ($troops as $tid => $tnum) {
				echo '			<td><img src="assets/x.gif" class="unit u';
				echo $tid;
				echo '" title="';
				echo constant( 'troop_' . $tid );
				echo '" alt="';
				echo constant( 'troop_' . $tid );
				echo '"></td>
			';
			}

			echo '			';

			if (( $hasHero && $procType == QS_WAR_REINFORCE )) {
				echo '			<td><img src="assets/x.gif" class="unit uhero" title="';
				echo troop_hero;
				echo '" alt="';
				echo troop_hero;
				echo '"></td>
			';
			}

			echo '		</tr>
		<tr>
			<th>';
			echo LANGUI_CUSTBU_RP_t6;
			echo '</th>
			';
			foreach ($troops as $tid => $tnum) {
				echo '			';

				if ($procType != QS_WAR_REINFORCE) {
					echo '<td class="none">?</td>';
					continue;
				}

				echo '			';

				if ($tnum == 0) {
					echo '<td class="none">0</td>';
				} 
else {
					echo '<td>';
					echo $tnum;
					echo '</td>';
				}

				echo '			';
			}

			echo '			';

			if (( $hasHero && $procType == QS_WAR_REINFORCE )) {
				echo '			<td>1</td>
			';
			}

			echo '		</tr>
	</tbody>
	<tbody class="infos">
		<tr>
			<th>';
			echo LANGUI_CUSTBU_RP_t7;
			echo '</th>
			<td colspan="';
			echo $colspan;
			echo '">
				<div class="in small">';
			echo text_in_lang;
			echo ' ';
			echo '<s';
			echo 'pan id="timer1">';
			echo WebHelper::secondstostring( $taskTable['remainingSeconds'] );
			echo '</span> ';
			echo time_hour_lang;
			echo '</div>
			</td>
		</tr>
	</tbody>
	';

			if ($resources != NULL) {
				echo '	<tbody class="infos">
		<tr>
			<th>';
				echo LANGUI_CUSTBU_RP_t8;
				echo '</th>
			<td colspan="';
				echo $colspan;
				echo '">
				<img class="r1" src="assets/x.gif" alt="';
				echo item_title_1;
				echo '" title="';
				echo item_title_1;
				echo '">';
				echo $resources[0];
				echo ' | 
				<img class="r2" src="assets/x.gif" alt="';
				echo item_title_2;
				echo '" title="';
				echo item_title_2;
				echo '">';
				echo $resources[1];
				echo ' | 
				<img class="r3" src="assets/x.gif" alt="';
				echo item_title_3;
				echo '" title="';
				echo item_title_3;
				echo '">';
				echo $resources[2];
				echo ' | 
				<img class="r4" src="assets/x.gif" alt="';
				echo item_title_4;
				echo '" title="';
				echo item_title_4;
				echo '">';
				echo $resources[3];
				echo '			</td>
		</tr>
	</tbody>
	';
			}

			echo '</table>
';
		}

		$m->dispose();
	}

	echo '

';

	if (0 < sizeof( $this->rallyPointProperty['war_from_village'] )) {
		
		$m = new BuildModel();
		echo '<h4>';
		echo LANGUI_CUSTBU_RP_t9;
		echo '</h4>
';
		foreach ($this->rallyPointProperty['war_from_village'] as $taskTable) {
			$procType = $taskTable['proc_type'];
			$_arr = explode( '|', $taskTable['proc_params'] );
			$resources = NULL;
			$action = '';
			switch ($procType) {
				case QS_WAR_REINFORCE: {
					$action = LANGUI_CUSTBU_RP_t10 . ' ';
					break;
				}

				case QS_WAR_ATTACK: {
					$action = LANGUI_CUSTBU_RP_t3 . ' ';
					break;
				}

				case QS_WAR_ATTACK_PLUNDER: {
					$action = LANGUI_CUSTBU_RP_t4 . ' ';
					break;
				}

				case QS_WAR_ATTACK_SPY: {
					$action = LANGUI_CUSTBU_RP_t11 . ' ';
					break;
				}

				case QS_CREATEVILLAGE: {
					$action = LANGUI_CUSTBU_RP_t12;
					$resources = explode( ' ', $_arr[4] );
				}
			}


			if ($procType != QS_CREATEVILLAGE) {
				$actionRow = $m->getVillageData2ById( $taskTable['to_village_id'] );

				if ($actionRow == NULL) {
					$action .= '<span class="none">[?]</span>';
				} 
else {
					if ($actionRow['is_oasis']) {
						$action .= (0 < intval( $actionRow['player_id'] ) ? LANGUI_CUSTBU_RP_t13 : LANGUI_CUSTBU_RP_t14);
					} 
else {
						$action .= (0 < intval( $actionRow['player_id'] ) ? $actionRow['village_name'] : '<span class="none">[?]</span>');
					}
				}
			}

			$troopsStr = explode( ',', $_arr[0] );
			$hasHero = FALSE;
			$troops = array();
			foreach ($troopsStr as $s) {
				list( $tid, $tnum ) = explode( ' ', $s );

				if ($tnum == 0 - 1) {
					$hasHero = TRUE;
					continue;
				}

				$troops[$tid] = $tnum;
			}

			$colspan = ($hasHero ? 11 : 10);
			echo '<table class="troop_details" cellpadding="1" cellspacing="1">
	<thead>
		<tr>
			<td class="role"><a href="village3.php?id=';
			echo $this->data['selected_village_id'];
			echo '">';
			echo $this->data['village_name'];
			echo '</a></td>
			<td colspan="';
			echo $colspan;
			echo '"><a href="village3.php?id=';
			echo $taskTable['to_village_id'];
			echo '"><p>';
			echo $action;
			echo '</p></a></td>
		</tr>
	</thead>
	<tbody class="units">
		<tr>
			<th>&nbsp;</th>
			';
			foreach ($troops as $tid => $tnum) {
				echo '			<td><img src="assets/x.gif" class="unit u';
				echo $tid;
				echo '" title="';
				echo constant( 'troop_' . $tid );
				echo '" alt="';
				echo constant( 'troop_' . $tid );
				echo '"></td>
			';
			}

			echo '			';

			if ($hasHero) {
				echo '			<td><img src="assets/x.gif" class="unit uhero" title="';
				echo troop_hero;
				echo '" alt="';
				echo troop_hero;
				echo '"></td>
			';
			}

			echo '		</tr>
		<tr>
			<th>';
			echo LANGUI_CUSTBU_RP_t6;
			echo '</th>
			';
			foreach ($troops as $tid => $tnum) {
				echo '			';

				if ($tnum == 0) {
					echo '<td class="none">0</td>';
				} 
else {
					echo '<td>';
					echo $tnum;
					echo '</td>';
				}

				echo '			';
			}

			echo '			';

			if ($hasHero) {
				echo '			<td>1</td>
			';
			}

			echo '		</tr>
	</tbody>
	<tbody class="infos">
		<tr>
			<th>';
			echo LANGUI_CUSTBU_RP_t7;
			echo '</th>
			<td colspan="';
			echo $colspan;
			echo '">
				<div class="in small">';
			echo text_in_lang;
			echo ' ';
			echo '<s';
			echo 'pan id="timer1">';
			echo WebHelper::secondstostring( $taskTable['remainingSeconds'] );
			echo '</span> ';
			echo time_hour_lang;
			echo '</div>
				';

			if ($this->_canCancelWarTask( $taskTable['proc_type'], $taskTable['id'] )) {
				echo '<div class="abort"><a href="build.php?id=39&d=';
				echo $taskTable['id'];
				echo '"><img src="assets/x.gif" class="del" title="';
				echo LANGUI_CUSTBU_RP_t27;
				echo '" alt="';
				echo LANGUI_CUSTBU_RP_t27;
				echo '"></a></div>';
			}

			echo '			</td>
		</tr>
	</tbody>
	';

			if ($resources != NULL) {
				echo '	<tbody class="infos">
		<tr>
			<th>';
				echo LANGUI_CUSTBU_RP_t15;
				echo '</th>
			<td colspan="';
				echo $colspan;
				echo '">
				<img class="r1" src="assets/x.gif" alt="';
				echo item_title_1;
				echo '" title="';
				echo item_title_1;
				echo '">';
				echo $resources[0];
				echo ' | 
				<img class="r2" src="assets/x.gif" alt="';
				echo item_title_2;
				echo '" title="';
				echo item_title_2;
				echo '">';
				echo $resources[1];
				echo ' | 
				<img class="r3" src="assets/x.gif" alt="';
				echo item_title_3;
				echo '" title="';
				echo item_title_3;
				echo '">';
				echo $resources[2];
				echo ' | 
				<img class="r4" src="assets/x.gif" alt="';
				echo item_title_4;
				echo '" title="';
				echo item_title_4;
				echo '">';
				echo $resources[3];
				echo '			</td>
		</tr>
	</tbody>
	';
			}

			echo '</table>
';
		}

		$m->dispose();
	}

	echo '

';

	if (( 0 < sizeof( $this->rallyPointProperty['troops_in_village']['troopsTable'] ) || 0 < sizeof( $this->rallyPointProperty['troops_in_village']['troopsIntrapTable'] ) )) {
		echo '<h4>';
		echo LANGUI_CUSTBU_RP_t16;
		echo '</h4>
';
		foreach ($this->rallyPointProperty['troops_in_village']['troopsTable'] as $vid => $troopTable) {
			$colspan = ($troopTable['hasHero'] ? 11 : 10);
			$canBack = TRUE;
			echo '<table class="troop_details" cellpadding="1" cellspacing="1">
	<thead>
		<tr>
			<td class="role">';

			if (0 < intval( $troopTable['villageData']['player_id'] )) {
				echo '<a href="village3.php?id=';
				echo $troopTable['villageData']['id'];
				echo '">';
				echo $troopTable['villageData']['village_name'];
				echo '</a>';
			} 
else {
				echo '<s';
				echo 'pan class="none">[?]</span>';
			}

			echo '</td>
			<td colspan="';
			echo $colspan;
			echo '"><a href="profile.php?uid=';
			echo $troopTable['villageData']['player_id'];
			echo '">';
			echo LANGUI_CUSTBU_RP_t17;
			echo ' ';

			if (0 < intval( $troopTable['villageData']['player_id'] )) {
				echo $troopTable['villageData']['player_name'];
			} 
else {
				echo '<s';
				echo 'pan class="none">[?]</span>';
			}

			echo '</a></td>
		</tr>
	</thead>
	<tbody class="units">
		<tr>
			<th>&nbsp;</th>
			';
			foreach ($troopTable['troops'] as $tid => $tnum) {
				if ($tid == 31) {
					$canBack = FALSE;
				}

				echo '			<td><img src="assets/x.gif" class="unit u';
				echo $tid;
				echo '" title="';
				echo constant( 'troop_' . $tid );
				echo '" alt="';
				echo constant( 'troop_' . $tid );
				echo '"></td>
			';
			}

			echo '			';

			if ($troopTable['hasHero']) {
				echo '			<td><img src="assets/x.gif" class="unit uhero" title="';
				echo troop_hero;
				echo '" alt="';
				echo troop_hero;
				echo '"></td>
			';
			}

			echo '		</tr>
		<tr>
			<th>';
			echo LANGUI_CUSTBU_RP_t6;
			echo '</th>
			';
			foreach ($troopTable['troops'] as $tid => $tnum) {
				echo '			';

				if ($tnum == 0) {
					echo '<td class="none">0</td>';
				} 
else {
					echo '<td>';
					echo $tnum;
					echo '</td>';
				}

				echo '			';
			}

			echo '			';

			if ($troopTable['hasHero']) {
				echo '			<td>1</td>
			';
			}

			echo '		</tr>
	</tbody>
	<tbody class="infos">
		<tr>
			<th>';
			echo LANGUI_CUSTBU_RP_t18;
			echo '</th>
			<td colspan="';
			echo $colspan;
			echo '">
				<div class="sup">';
			echo $troopTable['cropConsumption'];
			echo '<img class="r4" src="assets/x.gif" title="';
			echo item_title_4;
			echo '" alt="';
			echo item_title_4;
			echo '"> ';
			echo LANGUI_CUSTBU_RP_t19;
			echo '</div>
				';

			if (( $troopTable['villageData']['id'] != $this->data['selected_village_id'] && $canBack )) {
				echo '<div class="gback"><a href="v2v.php?d1=';
				echo $troopTable['villageData']['id'];
				echo '">';
				echo LANGUI_CUSTBU_RP_t20;
				echo '</a></div>';
			}

			echo '			</td>
		</tr>
	</tbody>
</table>
';
		}

		foreach ($this->rallyPointProperty['troops_in_village']['troopsIntrapTable'] as $vid => $troopTable) {
			$colspan = ($troopTable['hasHero'] ? 11 : 10);
			echo '<table class="troop_details" cellpadding="1" cellspacing="1">
	<thead>
		<tr>
			<td class="role">';

			if (0 < intval( $troopTable['villageData']['player_id'] )) {
				echo '<a href="village3.php?id=';
				echo $troopTable['villageData']['id'];
				echo '">';
				echo $troopTable['villageData']['village_name'];
				echo '</a>';
			} 
else {
				echo '<s';
				echo 'pan class="none">[?]</span>';
			}

			echo '</td>
			<td colspan="';
			echo $colspan;
			echo '"><a href="profile.php?uid=';
			echo $troopTable['villageData']['player_id'];
			echo '">';
			echo LANGUI_CUSTBU_RP_t17;
			echo ' ';

			if (0 < intval( $troopTable['villageData']['player_id'] )) {
				echo $troopTable['villageData']['player_name'];
			} 
else {
				echo '<s';
				echo 'pan class="none">[?]</span>';
			}

			echo ' ';
			echo LANGUI_CUSTBU_RP_t21;
			echo '</a></td>
		</tr>
	</thead>
	<tbody class="units">
		<tr>
			<th>&nbsp;</th>
			';
			foreach ($troopTable['troops'] as $tid => $tnum) {
				echo '			<td><img src="assets/x.gif" class="unit u';
				echo $tid;
				echo '" title="';
				echo constant( 'troop_' . $tid );
				echo '" alt="';
				echo constant( 'troop_' . $tid );
				echo '"></td>
			';
			}

			echo '			';

			if ($troopTable['hasHero']) {
				echo '			<td><img src="assets/x.gif" class="unit uhero" title="';
				echo troop_hero;
				echo '" alt="';
				echo troop_hero;
				echo '"></td>
			';
			}

			echo '		</tr>
		<tr>
			<th>';
			echo LANGUI_CUSTBU_RP_t6;
			echo '</th>
			';
			foreach ($troopTable['troops'] as $tid => $tnum) {
				echo '			';

				if ($tnum == 0) {
					echo '<td class="none">0</td>';
				} 
else {
					echo '<td>';
					echo $tnum;
					echo '</td>';
				}

				echo '			';
			}

			echo '			';

			if ($troopTable['hasHero']) {
				echo '			<td>1</td>
			';
			}

			echo '		</tr>
	</tbody>
	<tbody class="infos">
		<tr>
			<th>';
			echo LANGUI_CUSTBU_RP_t18;
			echo '</th>
			<td colspan="';
			echo $colspan;
			echo '">
				<div class="sup">';
			echo $troopTable['cropConsumption'];
			echo '<img class="r4" src="assets/x.gif" title="';
			echo item_title_4;
			echo '" alt="';
			echo item_title_4;
			echo '"> ';
			echo LANGUI_CUSTBU_RP_t19;
			echo '</div>
				<div class="gback"><a href="v2v.php?d2=';
			echo $troopTable['villageData']['id'];
			echo '">';
			echo LANGUI_CUSTBU_RP_t22;
			echo '</a></div>
			</td>
		</tr>
	</tbody>
</table>
';
		}
	}

	echo '
';

	if (( 0 < sizeof( $this->rallyPointProperty['troops_out_village']['troopsTable'] ) || 0 < sizeof( $this->rallyPointProperty['troops_out_village']['troopsIntrapTable'] ) )) {
		echo '<h4>';
		echo LANGUI_CUSTBU_RP_t23;
		echo '</h4>
';
		foreach ($this->rallyPointProperty['troops_out_village']['troopsTable'] as $vid => $troopTable) {
			$colspan = ($troopTable['hasHero'] ? 11 : 10);
			echo '<table class="troop_details" cellpadding="1" cellspacing="1">
	<thead>
		<tr>
			<td class="role">';

			if (0 < intval( $troopTable['villageData']['player_id'] )) {
				echo '<a href="village3.php?id=';
				echo $troopTable['villageData']['id'];
				echo '">';
				echo $troopTable['villageData']['village_name'];
				echo '</a>';
			} 
else {
				echo '<s';
				echo 'pan class="none">[?]</span>';
			}

			echo '</td>
			<td colspan="';
			echo $colspan;
			echo '"><a href="profile.php?uid=';
			echo $troopTable['villageData']['player_id'];
			echo '">';
			echo LANGUI_CUSTBU_RP_t10;
			echo ' ';

			if (0 < intval( $troopTable['villageData']['player_id'] )) {
				echo $troopTable['villageData']['player_name'];
			} 
else {
				echo '<s';
				echo 'pan class="none">[?]</span>';
			}

			echo '</a></td>
		</tr>
	</thead>
	<tbody class="units">
		<tr>
			<th>&nbsp;</th>
			';
			foreach ($troopTable['troops'] as $tid => $tnum) {
				echo '			<td><img src="assets/x.gif" class="unit u';
				echo $tid;
				echo '" title="';
				echo constant( 'troop_' . $tid );
				echo '" alt="';
				echo constant( 'troop_' . $tid );
				echo '"></td>
			';
			}

			echo '			';

			if ($troopTable['hasHero']) {
				echo '			<td><img src="assets/x.gif" class="unit uhero" title="';
				echo troop_hero;
				echo '" alt="';
				echo troop_hero;
				echo '"></td>
			';
			}

			echo '		</tr>
		<tr>
			<th>';
			echo LANGUI_CUSTBU_RP_t6;
			echo '</th>
			';
			foreach ($troopTable['troops'] as $tid => $tnum) {
				echo '			';

				if ($tnum == 0) {
					echo '<td class="none">0</td>';
				} 
else {
					echo '<td>';
					echo $tnum;
					echo '</td>';
				}

				echo '			';
			}

			echo '			';

			if ($troopTable['hasHero']) {
				echo '			<td>1</td>
			';
			}

			echo '		</tr>
	</tbody>
	<tbody class="infos">
		<tr>
			<th>';
			echo LANGUI_CUSTBU_RP_t18;
			echo '</th>
			<td colspan="';
			echo $colspan;
			echo '">
				<div class="sup">';
			echo $troopTable['cropConsumption'];
			echo '<img class="r4" src="assets/x.gif" title="';
			echo item_title_4;
			echo '" alt="';
			echo item_title_4;
			echo '"> ';
			echo LANGUI_CUSTBU_RP_t19;
			echo '</div>
				<div class="gback"><a href="v2v.php?d3=';
			echo $troopTable['villageData']['id'];
			echo '">';
			echo LANGUI_CUSTBU_RP_t24;
			echo '</a></div>
			</td>
		</tr>
	</tbody>
</table>
';
		}

		foreach ($this->rallyPointProperty['troops_out_village']['troopsIntrapTable'] as $vid => $troopTable) {
			$colspan = ($troopTable['hasHero'] ? 11 : 10);
			echo '<table class="troop_details" cellpadding="1" cellspacing="1">
	<thead>
		<tr>
			<td class="role">';

			if (0 < intval( $troopTable['villageData']['player_id'] )) {
				echo '<a href="village3.php?id=';
				echo $troopTable['villageData']['id'];
				echo '">';
				echo $troopTable['villageData']['village_name'];
				echo '</a>';
			} 
else {
				echo '<s';
				echo 'pan class="none">[?]</span>';
			}

			echo '</td>
			<td colspan="';
			echo $colspan;
			echo '"><a href="profile.php?uid=';
			echo $troopTable['villageData']['player_id'];
			echo '">';
			echo LANGUI_CUSTBU_RP_t25;
			echo ' ';

			if (0 < intval( $troopTable['villageData']['player_id'] )) {
				echo $troopTable['villageData']['player_name'];
			} 
else {
				echo '<s';
				echo 'pan class="none">[?]</span>';
			}

			echo '</a></td>
		</tr>
	</thead>
	<tbody class="units">
		<tr>
			<th>&nbsp;</th>
			';
			foreach ($troopTable['troops'] as $tid => $tnum) {
				echo '			<td><img src="assets/x.gif" class="unit u';
				echo $tid;
				echo '" title="';
				echo constant( 'troop_' . $tid );
				echo '" alt="';
				echo constant( 'troop_' . $tid );
				echo '"></td>
			';
			}

			echo '			';

			if ($troopTable['hasHero']) {
				echo '			<td><img src="assets/x.gif" class="unit uhero" title="';
				echo troop_hero;
				echo '" alt="';
				echo troop_hero;
				echo '"></td>
			';
			}

			echo '		</tr>
		<tr>
			<th>';
			echo LANGUI_CUSTBU_RP_t6;
			echo '</th>
			';
			foreach ($troopTable['troops'] as $tid => $tnum) {
				echo '			';

				if ($tnum == 0) {
					echo '<td class="none">0</td>';
				} 
else {
					echo '<td>';
					echo $tnum;
					echo '</td>';
				}

				echo '			';
			}

			echo '			';

			if ($troopTable['hasHero']) {
				echo '			<td>1</td>
			';
			}

			echo '		</tr>
	</tbody>
	<tbody class="infos">
		<tr>
			<th>';
			echo LANGUI_CUSTBU_RP_t18;
			echo '</th>
			<td colspan="';
			echo $colspan;
			echo '">
				<div class="sup">';
			echo $troopTable['cropConsumption'];
			echo '<img class="r4" src="assets/x.gif" title="';
			echo item_title_4;
			echo '" alt="';
			echo item_title_4;
			echo '"> ';
			echo LANGUI_CUSTBU_RP_t19;
			echo '</div>
			</td>
		</tr>
	</tbody>
</table>
';
		}
	}

	echo '

';

	if (0 < sizeof( $this->rallyPointProperty['troops_in_oases'] )) {
		foreach ($this->rallyPointProperty['troops_in_oases'] as $oasisId => $oasisData) {
			if (( sizeof( $oasisData['troopsTable'] ) == 0 && sizeof( $oasisData['war_to'] ) == 0 )) {
				continue;
			}

			echo '<br/><p class="info"><a href="village3.php?id=';
			echo $oasisId;
			echo '">';
			echo LANGUI_CUSTBU_RP_t26;
			echo ' (';
			echo $oasisData['oasisRow']['rel_x'];
			echo '|';
			echo $oasisData['oasisRow']['rel_y'];
			echo ')</a></p>

';

			if (0 < sizeof( $oasisData['war_to'] )) {
				
				$m = new BuildModel();
				echo '<h4>';
				echo LANGUI_CUSTBU_RP_t1;
				echo '</h4>
';
				foreach ($oasisData['war_to'] as $taskTable) {
					$procType = $taskTable['proc_type'];
					$action1 = '';
					switch ($procType) {
						case QS_WAR_REINFORCE: {
							$action1 = LANGUI_CUSTBU_RP_t10;
							break;
						}

						case QS_WAR_ATTACK: {
							$action1 = LANGUI_CUSTBU_RP_t3;
							break;
						}

						case QS_WAR_ATTACK_PLUNDER: {
							$action1 = LANGUI_CUSTBU_RP_t4;
						}
					}

					$action1 .= ' ' . LANGUI_CUSTBU_RP_t26;
					$action2 = '';
					$actionRow = $m->getVillageData2ById( $taskTable['village_id'] );

					if (( $actionRow == NULL || intval( $actionRow['player_id'] ) != intval( $taskTable['player_id'] ) )) {
						$action2 .= '<span class="none">[?]</span>';
					} 
else {
						$action2 .= ($actionRow['tribe_id'] == 4 ? LANGUI_CUSTBU_RP_t5 : $actionRow['village_name']);
					}

					$_arr = explode( '|', $taskTable['proc_params'] );
					$troopsStr = explode( ',', $_arr[0] );
					$hasHero = FALSE;
					$troops = array();
					foreach ($troopsStr as $s) {
						list( $tid, $tnum ) = explode( ' ', $s );

						if ($tnum == 0 - 1) {
							$hasHero = TRUE;
							continue;
						}

						$troops[$tid] = $tnum;
					}

					$colspan = (( $hasHero && $procType == QS_WAR_REINFORCE ) ? 11 : 10);
					echo '<table class="troop_details" cellpadding="1" cellspacing="1">
	<thead>
		<tr>
			<td class="role">';

					if ($action2 != '') {
						echo '<a href="village3.php?id=';
						echo $taskTable['village_id'];
						echo '">';
						echo $action2;
						echo '</a>';
					} 
else {
						echo $action2;
					}

					echo '</td>
			<td colspan="';
					echo $colspan;
					echo '"><a href="village3.php?id=';
					echo $taskTable['to_village_id'];
					echo '"><p>';
					echo $action1;
					echo '</p></a></td>
		</tr>
	</thead>
	<tbody class="units">
		<tr>
			<th>&nbsp;</th>
			';
					foreach ($troops as $tid => $tnum) {
						echo '			<td><img src="assets/x.gif" class="unit u';
						echo $tid;
						echo '" title="';
						echo constant( 'troop_' . $tid );
						echo '" alt="';
						echo constant( 'troop_' . $tid );
						echo '"></td>
			';
					}

					echo '			';

					if (( $hasHero && $procType == QS_WAR_REINFORCE )) {
						echo '			<td><img src="assets/x.gif" class="unit uhero" title="';
						echo troop_hero;
						echo '" alt="';
						echo troop_hero;
						echo '"></td>
			';
					}

					echo '		</tr>
		<tr>
			<th>';
					echo LANGUI_CUSTBU_RP_t6;
					echo '</th>
			';
					foreach ($troops as $tid => $tnum) {
						echo '			';

						if ($procType != QS_WAR_REINFORCE) {
							echo '<td class="none">?</td>';
							continue;
						}

						echo '			';

						if ($tnum == 0) {
							echo '<td class="none">0</td>';
						} 
else {
							echo '<td>';
							echo $tnum;
							echo '</td>';
						}

						echo '			';
					}

					echo '			';

					if (( $hasHero && $procType == QS_WAR_REINFORCE )) {
						echo '			<td>1</td>
			';
					}

					echo '		</tr>
	</tbody>
	<tbody class="infos">
		<tr>
			<th>';
					echo LANGUI_CUSTBU_RP_t7;
					echo '</th>
			<td colspan="';
					echo $colspan;
					echo '">
				<div class="in small">';
					echo text_in_lang;
					echo ' ';
					echo '<s';
					echo 'pan id="timer1">';
					echo WebHelper::secondstostring( $taskTable['remainingSeconds'] );
					echo '</span> ';
					echo time_hour_lang;
					echo '</div>
			</td>
		</tr>
	</tbody>
</table>
';
				}

				$m->dispose();
			}

			echo '
';

			if (0 < sizeof( $oasisData['troopsTable'] )) {
				echo '<h4>';
				echo LANGUI_CUSTBU_RP_t16;
				echo '</h4>
';
				foreach ($oasisData['troopsTable'] as $vid => $troopTable) {
					$colspan = ($troopTable['hasHero'] ? 11 : 10);
					echo '<table class="troop_details" cellpadding="1" cellspacing="1">
	<thead>
		<tr>
			<td class="role">';

					if (0 < intval( $troopTable['villageData']['player_id'] )) {
						echo '<a href="village3.php?id=';
						echo $troopTable['villageData']['id'];
						echo '">';
						echo $troopTable['villageData']['village_name'];
						echo '</a>';
					} 
else {
						echo '<s';
						echo 'pan class="none">[?]</span>';
					}

					echo '</td>
			<td colspan="';
					echo $colspan;
					echo '"><a href="profile.php?uid=';
					echo $troopTable['villageData']['player_id'];
					echo '">';
					echo LANGUI_CUSTBU_RP_t17;
					echo ' ';

					if (0 < intval( $troopTable['villageData']['player_id'] )) {
						echo $troopTable['villageData']['player_name'];
					} 
else {
						echo '<s';
						echo 'pan class="none">[?]</span>';
					}

					echo '</a></td>
		</tr>
	</thead>
	<tbody class="units">
		<tr>
			<th>&nbsp;</th>
			';
					foreach ($troopTable['troops'] as $tid => $tnum) {
						echo '			<td><img src="assets/x.gif" class="unit u';
						echo $tid;
						echo '" title="';
						echo constant( 'troop_' . $tid );
						echo '" alt="';
						echo constant( 'troop_' . $tid );
						echo '"></td>
			';
					}

					echo '			';

					if ($troopTable['hasHero']) {
						echo '			<td><img src="assets/x.gif" class="unit uhero" title="';
						echo troop_hero;
						echo '" alt="';
						echo troop_hero;
						echo '"></td>
			';
					}

					echo '		</tr>
		<tr>
			<th>';
					echo LANGUI_CUSTBU_RP_t6;
					echo '</th>
			';
					foreach ($troopTable['troops'] as $tid => $tnum) {
						echo '			';

						if ($tnum == 0) {
							echo '<td class="none">0</td>';
						} 
else {
							echo '<td>';
							echo $tnum;
							echo '</td>';
						}

						echo '			';
					}

					echo '			';

					if ($troopTable['hasHero']) {
						echo '			<td>1</td>
			';
					}

					echo '		</tr>
	</tbody>
	<tbody class="infos">
		<tr>
			<th>';
					echo LANGUI_CUSTBU_RP_t18;
					echo '</th>
			<td colspan="';
					echo $colspan;
					echo '">
				<div class="sup">';
					echo $troopTable['cropConsumption'];
					echo '<img class="r4" src="assets/x.gif" title="';
					echo item_title_4;
					echo '" alt="';
					echo item_title_4;
					echo '"> ';
					echo LANGUI_CUSTBU_RP_t19;
					echo '</div>
				<div class="gback"><a href="v2v.php?d1=';
					echo $troopTable['villageData']['id'];
					echo '&o=';
					echo $oasisId;
					echo '">';
					echo LANGUI_CUSTBU_RP_t20;
					echo '</a></div>
			</td>
		</tr>
	</tbody>
</table>
';
				}

				continue;
			}
		}
	}

?>

