<?php
	// hotfix for non static methods adding it here since there is multiple places where static method was called
	// easier to call new class once and call the function from it once we need it, than create new class all the time right?
	$webhelper_client = new WebHelper();
	
	require_once( LANG_UI_PATH . 'custbuilds.php' );
	echo '<p></p>
';

	if ($this->buildings[$this->buildingIndex]['item_id'] == 36) {
		echo '<p>';
		echo LANGUI_CUSTBU_TRP_t1;
		echo ' <b>';
		echo $this->troops[99];
		echo '</b> ';
		echo LANGUI_CUSTBU_TRP_t2;
		echo ' <b>';
		echo $this->data['troops_trapped_num'];
		echo '</b> ';
		echo LANGUI_CUSTBU_TRP_t3;
		echo '.</p>
<p></p>
';
	}
	
	echo '<form method="post" name="snd" action="build.php?id=';
	echo $this->buildingIndex;
	echo '">
<table cellpadding="1" cellspacing="1" class="build_details">
	<thead>
		<tr>
			<td>';
	echo LANGUI_CUSTBU_TRP_t4;
	echo '</td>
			<td>';
	echo LANGUI_CUSTBU_TRP_t5;
	echo '</td>
			<td>';
	echo LANGUI_CUSTBU_TRP_t6;
	echo '</td>
		</tr>
	</thead>
	<tbody>
		';
	$_ac = 0;
	foreach ($this->troopsUpgrade as $tid) {
		++$_ac;
		$buildingMetadata = $this->gameMetadata['troops'][$tid];
		$timeFactor = 1;

		if ($buildingMetadata['is_cavalry'] == TRUE) {
			$flvl = $this->_getMaxBuildingLevel( 41 );

			if (0 < $flvl) {
				$timeFactor -= $this->gameMetadata['items'][41]['levels'][$flvl - 1]['value'] / 100;
			}
		}
		
		
		$lvlTime = intval( $buildingMetadata['training_time_consume'] / $this->gameSpeed * ( 10 / ( $this->buildProperties['building']['level'] + 9 ) ) * $timeFactor );
		$maxNumber = $this->_getMaxTrainNumber( $tid, $this->buildings[$this->buildingIndex]['item_id'] );
		$manual = ($tid == 99 ? '4,36' : '3,' . $tid);
		echo '		<tr>
			<td class="desc">
				<div class="tit"><img class="unit u';
		echo $tid;
		echo '" src="assets/x.gif" alt="';
		echo constant( 'troop_' . $tid );
		echo '" title="';
		echo constant( 'troop_' . $tid );
		echo '"><a href="#" onclick="return showManual(';
		echo $manual;
		echo ');">';
		echo constant( 'troop_' . $tid );
		echo '</a> ';
		echo '<s';
		echo 'pan class="info">(';
		echo LANGUI_CUSTBU_TRP_t7;
		echo ': ';
		echo $this->troops[$tid];
		echo ')</span></div>
				<div class="details">
					<img class="r1" src="assets/x.gif" alt="';
		echo item_title_1;
		echo '" title="';
		echo item_title_1;
		echo '">';
		echo '<s';
		echo 'pan class="little_res">';
		echo $buildingMetadata['training_resources'][1] * $this->buildingTribeFactor;
		echo '</span>|<img class="r2" src="assets/x.gif" alt="';
		echo item_title_2;
		echo '" title="';
		echo item_title_2;
		echo '">';
		echo '<s';
		echo 'pan class="little_res">';
		echo $buildingMetadata['training_resources'][2] * $this->buildingTribeFactor;
		echo '</span>|<img class="r3" src="assets/x.gif" alt="';
		echo item_title_3;
		echo '" title="';
		echo item_title_3;
		echo '">';
		echo '<s';
		echo 'pan class="little_res">';
		echo $buildingMetadata['training_resources'][3] * $this->buildingTribeFactor;
		echo '</span>|<img class="r4" src="assets/x.gif" alt="';
		echo item_title_4;
		echo '" title="';
		echo item_title_4;
		echo '">';
		echo '<s';
		echo 'pan class="little_res">';
		echo $buildingMetadata['training_resources'][4] * $this->buildingTribeFactor;
		echo '</span>|<img class="clock" src="assets/x.gif" alt="';
		echo text_period_lang;
		echo '" title="';
		echo text_period_lang;
		echo '">';
		echo $webhelper_client->secondstostring( $lvlTime );
	$neededResources = array(  );
	foreach ($buildingMetadata['training_resources'] as $k => $v) {
		$neededResources[$k] = $v * $this->buildingTribeFactor;
	}
	
	$vero = TRUE;
	echo $this->getResourceGoldExchange( $neededResources, 0, $this->buildingIndex, $vero );
		echo '				</div>
			</td>
			<td class="val"><input type="text" class="text" id="_tf';
		echo $tid;
		echo '" name="tf[';
		echo $tid;
		echo ']" value="0" maxlength="4"></td>
			<td class="max"><a href="#" onclick="_(\'_tf';
		echo $tid;
		echo '\').value=';
		echo $maxNumber;
		echo '; return false;">(';
		echo $maxNumber;
		echo ')</a></td>
		</tr>
		';
	}

	echo '		';

	if ($_ac == 0) {
		echo '		<tr><td colspan="3">';
		echo '<s';
		echo 'pan class="none">';
		echo LANGUI_CUSTBU_TRP_t8;
		echo '</span></td></tr>
		';
	}

	echo '	</tbody>
</table>
';

	if (0 < $_ac) {
		echo '<p><input type="image" id="btn_train" class="dynamic_img" value="ok" name="s1" src="assets/x.gif" alt="';
		echo LANGUI_CUSTBU_TRP_t9;
		echo '"></p>';
	}

	echo '</form>
';

	if (( isset( $this->queueModel->tasksInQueue[$this->troopsUpgradeType] ) && isset( $this->queueModel->tasksInQueue[$this->troopsUpgradeType][$this->buildProperties['building']['item_id']] ) )) {
		$qts = $this->queueModel->tasksInQueue[$this->troopsUpgradeType][$this->buildProperties['building']['item_id']];
		echo '<table cellpadding="1" cellspacing="1" class="under_progress">
	';

		if (( !$this->data['is_special_village'] && $this->gameMetadata['plusTable'][7]['cost'] <= $this->data['gold_num'] )) {
			echo '	<thead>
		<tr>
			<th colspan="2">
				';
			$costTip = sprintf( LANGUI_CUSTBU_TRP_t15, $this->gameMetadata['plusTable'][7]['cost'] );
			echo '				';
			echo LANGUI_CUSTBU_TRP_t16;
			echo ': 
				<a href="village1.php?tfs&k=';
			echo $this->data['update_key'];
			echo '" title="';
			echo $costTip;
			echo '">
				<img class="clock" alt="';
			echo $costTip;
			echo '" src="assets/x.gif"></a>
			</th>
		</tr>
	</thead>
	';
		}

		echo '	<thead>
		<tr>
			<td>';

		if ($this->buildProperties['building']['item_id'] == 36) {
			echo LANGUI_CUSTBU_TRP_t10;
		} 
else {
			echo LANGUI_CUSTBU_TRP_t11;
		}

		echo '</td>
			<td>';
		echo text_period_lang;
		echo '</td>
		</tr>
	</thead>
	<tbody>
		';
		$nextTroopTime = 0;
		$_f = TRUE;
		foreach ($qts as $qt) {
			$tid = $qt['proc_params'];
			$troopTime = $qt['execution_time'] - ( $qt['execution_time'] * $qt['threads'] - $qt['remainingSeconds'] );

			if (( $troopTime < $nextTroopTime || $_f )) {
				$_f = FALSE;
				$nextTroopTime = $troopTime;
			}
			echo '		<tr>
			<td class="desc"><img class="unit u';
			echo $tid;
			echo '" src="assets/x.gif" alt="';
			echo constant( 'troop_' . $tid );
			echo '" title="';
			echo constant( 'troop_' . $tid );
			echo '"> ';
			echo $qt['threads'];
			echo ' ';
			echo constant( 'troop_' . $tid );
			echo '</td>
			<td class="dur">';
			echo '<s';
			echo 'pan id="timer1">';
			echo $webhelper_client->secondstostring( $qt['remainingSeconds'] );
			echo '</span></td>
		</tr>
		';
		}
		echo '		<tr class="next"><td colspan="2">';
		echo ($this->buildProperties['building']['item_id'] == 36 ? LANGUI_CUSTBU_TRP_t13 : LANGUI_CUSTBU_TRP_t14);
		echo ' ';
		echo LANGUI_CUSTBU_TRP_t12;
		echo ' ';
		echo '<s';
		echo 'pan id="timer1">';
		echo $webhelper_client->secondstostring( $nextTroopTime );
		echo '</span></td></tr>
	</tbody>
</table>
';
	}

?>

