<?php
	echo '<!-- By Bazaid @ DAFED Team --!>';
	require_once( LANG_UI_PATH . 'footer.php' );
	echo '<ul class="menu menu2">
	<li><a href="index.php">';
	echo LANGUI_FOOTER_MAIN;
	echo '</a></li>
	<li><a href="manual.php">';
	echo LANGUI_FOOTER_MANUAL;
	echo '</a></li>
	<li><a href="training.php">';
	echo LANGUI_FOOTER_TRAINING;
	echo '</a></li>
	<li><a href="http://www.dafedteam.com" target="_blank">Copyright &copy; To Bazaid,DAFED Team</a></li>
</ul>';
?>
